### ISSUE TITLE
Make leader leases actual leases

### ISSUE THREAD

**Issue by jellevandenhooff** [hashicorp/raft#108]
The current version of the library supports leases, but these leases are not quite leases in the traditional sense. Traditional leases come with guarantees that no one else will be able to obtain a conflicting lease while the lease is valid, yet the current leases do not come with such guarantees. This was originally revealed by Jepsen testing, summarized in a [consul consistency gist](https://gist.github.com/armon/11059431), and resulted in Consul's [funny consensus modes](https://www.consul.io/docs/internals/consensus.html) where "default" is not quite consistent and "consistent" introduces extra latency.

This issue proposes to have leaders wait a period of LeaderLeaseTimeout at the beginning of their term to make leases correct. This delay would make all reads behave as consistent reads, at the cost of slightly longer elections. With the default leader lease timeout of 500ms in both Consul and Nomad, I think this is a reasonable trade-off to make.

For background, the [extended Raft paper](https://ramcloud.stanford.edu/raft.pdf) mentions leases at the end of section 8:

> Second, a leader must check whether it has been deposed before processing a read-only request (its information may be stale if a more recent leader has been elected). Raft handles this by having the leader exchange heartbeat messages with a majority of the cluster before responding to read-only requests. Alternatively, the leader could rely on the heartbeat mechanism to provide a form of lease [9], but this would rely on timing for safety (it assumes bounded clock skew).

Consul's "consistent" reads work with the prescribed method of exchanging heartbeats to verify leadership. Consul's "default" reads attempt to implement leases as prescribed end of the paragraph, but the paragraph does not quite provide enough guidance to do so safely:

The library currently uses the function checkLeaderLease in raft.go to verify if a leader is still the leader. That function checks if the leader has contacted at least a quorum of nodes in LeaderLeaseTimeout. While this provides a good heuristic for the leader still being the leader, it does not provide any guarantees. Specifically, consider the following scenario, with three nodes A, B, C. Node A starts out at as the leader. Node A and C are partitioned and can not communicate with each other, but both can reach node B:

T1: A sends a heartbeat to A, B, and C. Because C is partitioned, it does not receive the heartbeat. A and B reply successfully. Now A believes its lease is valid.
T2, before the lease has expired: C, being partitioned, has not heard from A for while, and decides to hold an election for itself. C requests a vote from A, B, and C with a new term. Because A is partitioned, it does not receive the vote request. Both B and C vote for C, as it is the only node currently up for election. Now C believes it is the leader for new term.
T3, still before A's lease has expired: C commits a write to the log. At the same time, A performs a read, serving stale data.
T4: A sends a new heartbeat to B, learns of the new term, and steps down.

This scenario is problematic because A at T3 still believes it holds a leader lease, while C has elected itself leader at T2. A mistakenly believes it holds the lease at T3 because B voted for A at T1, yet B has already voted for C at T2. A only learns it is no longer the leader at T4.

I can think of two possible solutions to this problem. One approach is to have B not vote for C until after A's lease expired, enforcing that T2 > T4. This is a traditional lease, where the voter promises not to vote for someone else for a given duration. Alternatively, C could wait a LeaderLeaseTimeout at the beginning of its term enforcing that T3 > T4. This way, C implicitly honors B's lease to A by waiting for the lease to expire.

While I believe both approaches would work, I prefer the simplicity of the second approach, requiring only a small logic change and not invasive changes to RequestVote's semantics. As mentioned above, the downside of this approach is that leader elections will always take a little longer. However, it is only a small increase, which would make the library more correct, and easier to use and reason about. An implementation detail to handle small clock skew would be to wait 1.1 times the LeaderLeaseTimeout.

Curious to hear your thoughts, @armon and @ongardie.

**Comment by jellevandenhooff** [comment]
Mentioning #84.

**Comment by armon** [comment]
@jellevandenhooff I think the existing implementation takes the first approach of refusing to vote for another candidate as long as we believe there is a leader:

https://github.com/hashicorp/raft/blob/master/raft.go#L1423

In the example you gave, B should reject the vote from C as a result so that A remains the leader. I would love a closer scrutiny since I maybe have missed a path that would allow this scenario to take place. I think the clock skew is an issue, and one strategy we've used is to use extremely conservative values by default for the timeouts so that you would need a very large clock skew to seriously impact Raft.

**Comment by jellevandenhooff** [comment]
Thanks for pointing that out! I've taken a closer look at the actual code, and feel pretty convinced the lease implementation is correct in most reasonable situations -- I do have some suggestions, but I don't know if they are worth the code churn.

My current understanding is as follows:

- On the follower side Raft.leader tracks who the follower has currently extended its lease to. It is set when AppendEntries succeeds or when InstallSnapshot succeeds. It is unset on state transition, or heartbeat timeout if Raft.lastContact is at least HeartbeatTimeout in the past. Raft.lastContact tracks when the follower extended its lease, and it is set whenever the client returns successfully, and also when stepping down.

- On the leader side, followerReplication.lastContact tracks (approximately) when a leader lease was issued per client. It is set after successful AppendEntries or InstallSnapshot calls. On the leader, checkLeaderLease is called repeatedly to cause the leader to step down when it needs to.

This looks like a good foundation for leader leases, but I have some worries:

1. The server starts its per-client timeout when it receives the client response, but that can be quite some time after the client has set Raft.leader. Perhaps the server could start a per-client timeout before sending the RPC.

2. The checkLeaderLease logic seems racy, as there is no guarantee that checkLeaderLease will be called in time to step down with Raft.state being updated in time. The code in consul/rpc.go seems dangerously optimistic as it assumes we are still the leader unless checkLeaderLease manages to run in time and change Raft.state to Follower. A safer pessimistic approach could be to expose the calculated leader lease timeout on the Raft struct. Consul could read that timeout before running the operation, execute the operation, and then check if the timeout has not yet passed before returning to the client.

3. The client lease timeout is implicit, relying on tricky interactions between Raft.leader and Raft.lastContact. I would have more faith in an implementation that set Raft.leader and Raft.lastContact in a single call with a single lock, with a guarantee that Raft.leader will not be until HeartbeatTimeout passes (unless a new leader has managed to elect itself with another quorum). Right now, I believe that guarantee is upheld because of the lastContact check in runFollower and because all setState calls look safe, but it is hard to be sure. If anything, I think it's worth documenting how Raft.lastContact and Raft.leader together function as a lease. Perhaps the heartbeatTimeout could be integrated with Raft.lastContact.

Because the code looks safe, I find it frustrating the Jepsen failed with "default" reads. 1. and 2. don't look perfect, but I find it hard to think of scenarios in which they could cause consistency violations:

I don't know if 1. could cause consistency violations in practice. It seems that the heartbeat timeout is large enough that any sufficiently delayed response would cause the leader to step down before the message arrived. However, tricky interplay of garbage collection, blocking writes, and network hiccups might cause problems. Similarly, 2. might cause consistency violations if a blocking StoreLogs inside of dispatchLogs could cause the timeout not to be checked for long enough. I can't think of scenarios where 3. would fail, but it is hard to be sure.

Kudos on the implementation!

**Comment by ongardie** [comment]
Hey @jellevandenhooff, nice to see you here too. Without jumping into the code, those seem like good suggestions to me. Regarding (3) about accessing Raft.leader and Raft.lastContact, that's in a broader class of concerns related to some of what's listed in #84 around accessing multiple fields while other goroutines might be operating on them. I'm hoping we can do some refactoring to "grow the critical sections" to make things more obviously correct. As you say, it can be hard to think of scenarios where the code would fail today, but it can also be hard to know for sure.

**Comment by abligh** [comment]
You might take a look at the last comment on https://github.com/hashicorp/raft/issues/107 - the lastContact stuff appears to be causing leaders to step down in high CPU conditions. I have suggested an alternative approach which would avoid this.

**Comment by jellevandenhooff** [comment]
Hi @abligh, I looked at #107. I don't think that your approach would be safe from a lease point of view, as leases would no longer timeout after you haven't heard from a client for a while. So I would prefer a solution to the underlying problem in #107 making sure that heartbeats keep happening even in high CPU situations. If that isn't possible, a safe yet complicated alternative might be to keep a timeout for leases, but to not necessarily step down when that lease expires.

**Comment by abligh** [comment]
@jellevandenhooff fair enough.

Another issue is that comparing `time.Now()` values and subtracting is not safe, particularly over small periods of time. As far as I can see, `time.Now()` is wall time, and is neither monotonic nor of a single frequency. This means it's subject to variations by NTP adjustment and leap seconds. So, for instance, with a 50ms lease.

    T1: leader gets lease
    T1+10ms: leap second adjustment, time goes back 1000ms
    T1+630ms (say): leader thinks it still has lease, as it reads time as T1-1000+630

The effects here are quite nasty. ntp slews time and will introduce subtle bugs. On leap seconds you're guaranteed either a leader stepdown or a period of 1 second of inconsistency (depending which way the leap second goes).

`time.Timer()` uses monotonic time instead. So the `lastContact()` stuff could be rewritten so:

* `setLastContact()` does a `timer.Reset()`
* Actions are triggered from the timer's channel.

Discussion here:
* https://codereview.appspot.com/53010043/
* https://github.com/golang/go/issues/12914
* https://groups.google.com/forum/#!topic/golang-dev/gVFa7DC8UI0

My read is that 1.4 changed the `time.Timer` (but not `time.Now()`) to use monotonic time on Linux AMD64, and that subsequently most of the other platforms have been fixed too.

So using functions that take a `time.Duration` is safe, but subtracting `time.Now()` values is not.
