### ISSUE TITLE
EnableSingleNode vs BootstrapExpect

### ISSUE THREAD

**Issue by advanderveer** [hashicorp/raft#114]
Hey There!

first off, awesome work on the quality of this library. I'm still trying to wrap my head around some of the edge cases Raft might run into, and as such I arrived at the bootstrap procedure. As you know, consul has the notion of 'bootstrap-expect' while this library seems to only provide the option "EnableSingleNode=false". This raises the following questions for me
1. Am I correct that just setting EnableSingleNode to false doesn't prevent split brain situations in scenario (A): while bootstrapping, a cluster of four nodes with a segmentation in the middle is able to create 2x2 peer lists with two leaders elected? In this case one would need an operator to tell each nodes how much members are expected in the cluster, i.e:
2. Would implementing a bootstrap-expect=N be as simple as just using some membership protocol and only start Raft ( raft.NewRaf() ) after N members were seen?
3. I'm also pondering an alternative: to make configuration more portable across a variety of cluster setups it would be handy for the bootstrap procedure to "timeout" after some period, this would throw bootstrap-expect=N out of the window and just work with whats available. This "BootstrapTimeout" would mean "_Ideally, wait for 5 members, but if your only seeing 3 after 2 minutes, just work with that_". The main upside here is that a configuration for a 5 member cluster could be used in 3 member cluster. This would reduce the mental effort for some users. The downside would be that 3 members might go rogue and make progress without 2 other members behind some network segmentation, correct?

I noticed this became more of a brainstorm, but i'm wondering what your thoughts are on these questions and If something like the last proposition might be useful to Consul, Nomad etc?

Cheers!

**Comment by slackpad** [comment]
Related to the first question - https://github.com/hashicorp/raft/issues/122.
