### ISSUE TITLE
Take an interface on WithLogger rather than *log.Logger

### ISSUE THREAD

**Issue by connor4312** [hashicorp/raft#141]
It'd be nice if an interface was accepted rather than requiring a *log.Logger struct so that logging could be further customized and swapped out other other systems (for instance, we use Logrus with a Sentry transport for centralized logging).

I'd be happy to put in a PR for this if there's interest.

**Comment by superfell** [comment]
This would be a good candidate to include for v2 @slackpad @ongardie

**Comment by ongardie** [comment]
@slackpad @superfell close-able now?

**Comment by slackpad** [comment]
I was going to leave this open until I switch over to logxi (see https://github.com/hashicorp/raft/pull/180#issuecomment-256726944). Working on that PR now.

**Comment by connor4312** [comment]
Thanks everyone 😄  Close at-will
