### ISSUE TITLE
Are entry indices guaranteed to be contiguous and starting from 1?

### ISSUE THREAD

**Issue by barrucadu** [hashicorp/raft#149]
Looking at [`dispatchLogs`](https://github.com/hashicorp/raft/blob/37bf1111efb0c6ba96a9c0e92adb51c2f858996a/raft.go#L1138) it looks like log entries have contiguous indices and are numbered from 1. The benchmarks don't respect this: the benchmark for [`StoreLog`](https://github.com/hashicorp/raft/blob/37bf1111efb0c6ba96a9c0e92adb51c2f858996a/raft.go#L1138) uses 0-indexing, and for [`StoreLogs`](https://github.com/hashicorp/raft/blob/master/bench/bench.go#L76) uses 0-indexing and non-contiguous indices.

I noticed this because I'm writing a `LogStore` implementation which assumes indices are identical to database insertion order (using 1-indexing, and modulo rolling back recent entries), so [I added a check](https://github.com/barrucadu/logdb/commit/27555654d7ef5541c5796f20fbaeae298a0a8c76) to my `StoreLog` and `StoreLogs` methods to return an error if that's not the case.  I then had to [revert that check](https://github.com/barrucadu/logdb/commit/e3fa6abe30a1aaea18c0eda0a07ec809a239f3a3) to make the benchmarks run, which isn't ideal.

Before I start blaming the benchmarks, I'd first like to check that I'm not misunderstanding something, and these cases could arise in normal execution. And if those cases can't arise normally, would you be open to a patch to the benchmarks bringing the behaviour more in-line with the main hashicorp/raft library?

**Comment by ongardie** [comment]
The indexing might start past 1 after log compaction, but there should never ever be an entry 0 in Raft.

**Comment by barrucadu** [comment]
Starting after 1 after compaction is fine, as long as originally there was a 1 inserted.

**Comment by ongardie** [comment]
If this is a new server added after the others have compacted and removed entry 1, then this server will never see entry 1.

**Comment by barrucadu** [comment]
Ah, of course. So I do need to keep track of the offset between "insertion order IDs" and log indices. And to make the `DeleteRange` benchmark work, I also need to keep track of the discontinuities.

Thanks.

**Comment by ongardie** [comment]
> And to make the DeleteRange benchmark work, I also need to keep track of the discontinuities.

Discontinuities? Raft doesn't allow gaps.

**Comment by slackpad** [comment]
It looks like the benchmarks are doing bad things. We should make them more realistic.

**Comment by barrucadu** [comment]
I decided tracking gaps just for the sake of benchmarks was too much like work, so I actually have a fork with the badness fixed. I'll submit a PR today.
