### ISSUE TITLE
Forcing a node to become leader without rebooting servers

### ISSUE THREAD

**Issue by deathzaplin** [hashicorp/raft#151]
I am trying to find a way to force a node to become the new leader while the server is running in response to changes in demand from clients near the servers location, is there a way to force a node to become leader and if not do you have any advice on how to implement this.

**Comment by ongardie** [comment]
Hi @deathzaplin. A similar question came up a few months ago with regards to the LogCabin project, and my answer would be pretty much the same here: https://groups.google.com/d/msg/logcabin-dev/LrpoEwCF77k/35DQrQJtAwAJ

If you did want to implement leadership transfer for hashicorp/raft, you should get buy-in from the hashicorp/raft maintainers here first. I'm not one of them, and I think they're a bit busy at the moment. Then probably do it as part of the issue-84-integration branch (issue #84) and probably further stacked atop my PR #136. I'd be happy to help work through the implementation plan and review changes.

**Comment by slackpad** [comment]
Hi @deathzaplin and @ongardie I think we'd be interested in this - it would be a useful capability to expose in tools like Consul, especially when performing upgrades.
