### ISSUE TITLE
How does the leader notice if one of the followers is down?

### ISSUE THREAD

**Issue by silentred** [hashicorp/raft#154]
Should the leader RemovePeer when it cannot communicate with one of the followers for a very long time?

**Comment by ThrosturX** [comment]
From what I can tell, if there's any chance of the follower rejoining, it's a bad idea as it might receive "removed self" and shut down on next contact.

**Comment by josephglanville** [comment]
Certain implementations do this.
Tt only really makes sense with either very large timeouts and additional logic that can determine if removing the peer is going to adversely affect durability or you have an external source of truth that you can verify that a peer is never coming back.

**Comment by silentred** [comment]
Removing a peer from raft group seems to be a rare and difficult operation.

**Comment by silentred** [comment]
@josephglanville Thanks a lot.

**Comment by s-christoff** [comment]
Hey @silentred, thank you so much for this question! In Consul we have [Autopilot](https://github.com/hashicorp/consul/tree/master/agent/consul/autopilot) which decides this for us. We support your program making this decision.
