### ISSUE TITLE
AddPeer race condition

### ISSUE THREAD

**Issue by abecciu** [hashicorp/raft#158]
I've recently run into a race condition while joining nodes concurrently to a cluster with the latest version the master branch. Here's the breakdown of what happened:

```
PeersStore = [1]
PreCommit AddPeer(2) -> (PeersStore = [1,2])
PreCommit AddPeer(3) -> (PeersStore = [1,2,3])
PreCommit AddPeer(4) -> (PeersStore = [1,2,3,4])
Commit AddPeer(2) -> (PeersStore = [1,2])
PreCommit AddPeer(5) -> (PeersStore = [1,2,5])
Commit AddPeer(3) -> (PeersStore = [1,2,3])
Commit AddPeer(4) -> (PeersStore = [1,2,3,4])
Commit AddPeer(5) -> (PeersStore = [1,2,5])
```

As you see, peers 3 and 4 get kicked out of the cluster without notifying the application layer since the log futures of `AddPeer(3)` and `AddPeer(4)` returned without error.

I know @ongardie is working on a complete overhaul of the internals, so it might be fixed in his branch. But I wanted to give the heads up just in case.

For now it's easy to prevent it from the application layer by not allowing concurrent calls to `AddPeer`.

**Comment by slackpad** [comment]
Hi @abecciu thanks for the heads up. This definitely should be covered under #84, specifically,  _Peer changes should have separate channel and do not pipeline (we don't want more than one peer change in flight at a time)_.
