### ISSUE TITLE
Changing addresses for a server

### ISSUE THREAD

**Issue by slackpad** [hashicorp/raft#162]
Right now we have a "barf on new address" todo that we need to resolve. Do we want to add support for changing addresses on the fly? If not we should return an error for this case.

**Comment by ongardie** [comment]
I accidentally and unintentionally changed my server address the other day when trying to add new members to my cluster. This happened because my source of "random" server IDs was not, in fact, random. So I vote for a different address being an error.

**Comment by slackpad** [comment]
Agree - it's better to have it an error until we actually support a change of address as a first-class thing.

**Comment by ongardie** [comment]
@slackpad, please close (I don't have permission)
