### ISSUE TITLE
Make the stats into a real structure

### ISSUE THREAD

**Issue by slackpad** [hashicorp/raft#167]
Clean up how configuration comes out in `Stats()`, the `"%+v"` formatting is weird / ugly. Also add a test to make sure it shows up (fixed a bug where the logic was wrong).

Better yet, make a new stats API that pulls the structure in one go w/o text.

**Comment by ongardie** [comment]
Another thing I wanted to do was to get at the term from my application (to ensure it hadn't changed across a period of time for reasons I can explain in gory detail). Should that be a new getTerm() or should this cover it?

**Comment by slackpad** [comment]
I think you'd get the term in this stats struct.

**Comment by ongardie-sfdc** [comment]
I think we should make getting this stats struct a proper query into the main raft.go goroutine over a channel. This would help a lot with #172 (merging state.go into raft.go).

**Comment by slackpad** [comment]
Yeah a future, similar to what we did for the configuration getter would be good for this as well.

**Comment by ongardie-sfdc** [comment]
btw I'm starting on this one.

**Comment by slackpad** [comment]
@ongardie-sfdc this one can be closed I think, right?

**Comment by ongardie** [comment]
@slackpad oh, I thought so but now I see the comment:

> Clean up how configuration comes out in Stats(), the "%+v" formatting is weird / ugly. Also add a test to make sure it shows up (fixed a bug where the logic was wrong).

Better check on that before we close it out.

**Comment by ongardie-sfdc** [comment]
PR #191 finishes this up.
