### ISSUE TITLE
[v2] Add new types for Index and Term

### ISSUE THREAD

**Issue by ongardie** [hashicorp/raft#171]
They're presently just uint64.

**Comment by ongardie** [comment]
I'll try to do this soon (today or Monday) since it'll conflict with just about every line of code.

**Comment by ongardie-sfdc** [comment]
@slackpad can you rename the issue-84-integration branch so I can base my PR off the new name?

**Comment by slackpad** [comment]
@ongardie sorry for the delay - https://github.com/hashicorp/raft/tree/library-v2-stage-two is up

**Comment by ongardie-sfdc** [comment]
@slackpad please close, as I may not.

**Comment by superfell** [comment]
This also has an effect on raft-boltdb
.godeps/src/github.com/hashicorp/raft-boltdb/bolt_store.go:146: cannot use log.Index (type raft.Index) as type uint64 in argument to uint64ToBytes
m

**Comment by slackpad** [comment]
@superfell indeed - it looks like we will need to maintain a branch of the bolt store as well. I made a library-v2 branch we can target a PR to.
