### ISSUE TITLE
[v2] log messages jumbled in tests

### ISSUE THREAD

**Issue by ongardie-sfdc** [hashicorp/raft#190]
For tests with MakeCluster(), I end up with multiple "servers" writing jumbled log messages with the new logxi stuff. It seems that we have multiple mutexes around writing log messages where there should be just one.

Also, while you're in there, logger.go has 80 lines of code commented out that can now be deleted.

**Comment by slackpad** [comment]
Ugh sorry I missed the commented out stuff - cleaned that up here - https://github.com/hashicorp/raft/commit/02ec98ced38d9f6a4eb05e47a421363457e9a62f. I'll see what's up with the jumbling.

**Comment by slackpad** [comment]
Sorry about that - logs should be good now.
