### ISSUE TITLE
Encrypted comms

### ISSUE THREAD

**Issue by jonbonazza** [hashicorp/raft#201]
Is it possible to add an option to encrypt rpc traffic? Even a simple symmetric key encryption of the message prior to sending (and the associated decryotion on the recieving end) would be helpful. Of course, this would be disabled by default, but app to app security is important for some use cases. :)

**Comment by josephglanville** [comment]
You can provide a custom Transport that encrypts RPCs, perhaps with this in mind it doesn't make sense to include it in the core library as everyones requirements for encryption and authentication are different?

**Comment by slackpad** [comment]
Agree with @josephglanville - we do exactly that up in Consul to use TLS (and to use a special connection multiplexer with other things connecting on the same port).

**Comment by otoolep** [comment]
FWIW, https://github.com/rqlite/rqlite also pushes a muxed transport into its use of the Hashicorp implementation.

https://github.com/rqlite/rqlite/blob/v3.10.0/cmd/rqlited/main.go#L158
https://github.com/rqlite/rqlite/blob/v3.10.0/cmd/rqlited/main.go#L162
https://github.com/rqlite/rqlite/blob/v3.10.0/cmd/rqlited/main.go#L174

I copied this pattern from InfluxDB.
