### ISSUE TITLE
Oddities with when logs are replaying during rolling deploy.

### ISSUE THREAD

**Issue by jonbonazza** [hashicorp/raft#204]
So I am trying to figure out the intended functionality with log replaying.

We are currently using VMs without persistent storage. In our raft cluster usage, we are using the boltdb log store implementation, which results in a memory-mapped file on disk. When we deploy a new version of the system, we perform a rolling deploy of the entire cluster, where each VM is taken down and redeployed 1 at a time. Since we don't have persistent storage, the boltdb file is obvisouly blown away, along with all of the other files we use for raft (json peers, snapshot, etc...).

We've noticed that during this rolling deploy, the last couple logs are replayed on the node that was just redeployed. If I understand correctly, the existing nodes' lastCommitIndex is > 0, while the newly redeployed node's index is 0, because there is not history on disk. Because of this discrepency, the last n logs are replayed. Is this correct?

Assuming it is, then I understand that the reason this is happening is because of that lack of persistent storage, yet trying to use a file store for maintaining cluster information.

However, if I try to reproduce this outside of a VM redeploy by shutting down the node, deleting all the files on the virtual disk, and then restarting the node, I would expect to see the logs replayed again, but I don't see this.

There seems to be a gap in my understanding of how log replays work across a cluster, and I can't quite grasp what is going on. Can someone please explain how this is intended to work, or at least point me to some documentation on how it is intended to work?

Thanks in advance.

**Comment by slackpad** [comment]
Hi @jonbonazza when a server is joined with completely fresh local storage, the leader will attempt to replicate older and older logs and then at some point will send the new follower a snapshot, followed by the logs that were created after the snapshot occurs. In that kind of case you'd get an initial snapshot install, and then a series of log updates played out to the state machine to catch it up. Does that seem to match what you may be seeing?

> However, if I try to reproduce this outside of a VM redeploy by shutting down the node, deleting all the files on the virtual disk, and then restarting the node, I would expect to see the logs replayed again, but I don't see this.

I can't see how this would cause any difference other than maybe the timing is such that there's not much to catch up on after the snapshot (a quiet cluster) - are there any other differences in your test setup that you can think of?

**Comment by jonbonazza** [comment]
@slackpad Yea, after reading through the white paper a few more times, it became clear that I'll need to implement a log driver that uses one of our persistent datastores.

As for the second oddity that you quoted, this is still baffling me. Is there a limit to how far back it will try to replicate? Also, it should be noted that, currently, every snapshot is completely empty:

```go
func (f *fsm) Snapshot() (raft.FSMSnapshot, error) {
	return &fsmSnapshot{}, nil
}
```

Will this cause any issues? From the white paper, I don't see any obvious reasons why I shouldn't do this, especially when there really isn't any state that I care to snapshot.

**Comment by knisbet** [comment]
@jonbonazza What you posted may cause you some issues.

If I understand correctly, what you're doing is telling raft that you've taken a snapshot of the store, but really haven't and just stored an empty one. The reason this might cause issues, is because raft will delete the logs leading up to a snapshot when a snapshot is taken (with some backlog as governed by raft.Config setting TrailingLogs). 

So now when you deploy a blank node, raft will try and restore the snapshot from another server, but it's blank, so you've now lost all those logs that the snapshot was supposed to contain. You'll just get a replay of the logs that have happened after the snapshot was taken.

The way I handled this before I implemented snapshot support in my code was:
```
func (f *fsm) Snapshot() (raft.FSMSnapshot, error) {
	return nil, fmt.Error("snapshot not supported")
}
```

By responding with an error, I basically told raft that the snapshot had failed, and in my test environment I didn't appear to lose any data due to a purge log, but I would say use at your own risk. 

Depending on your use case, you may eventually want to implement snapshot support, as the longer the service runs, the longer the log will get, and the longer a startup will take to replay the log. On my system when I was testing 1.5 million entries, it was taking a good couple minutes for a node to start, even when replaying the log locally.

**Comment by jonbonazza** [comment]
@knisbet
The snapshot is a snapsot if the application state, right? What if the app has no state to snapshot?

**Comment by jonbonazza** [comment]
@superfell i meant that I have no state that i care about persisting.

**Comment by knisbet** [comment]
@jonbonazza You are correct. 

The snapshot would be the application state, or in other words, a representation of what every log up to the snapshot changed in the application. If the application persists that application state as a snapshot, then we don't need the logs leading up to that point any more, we have a copy of the results of every change that was made. So if we don't have snapshots and run a busy raft cluster for a year, and then restart it, if we only had the log, we would have to replay a year's worth of data to rebuild the current application state.

If you have no state you care about persisting, than what your doing appears to achieve your goals based on my understanding of the hashicorp raft implementation. You can likely also tweak your configuration, to make snapshots occur more frequently, which means less replayed events when you start a fresh node. And by saving a snapshot that discards the data, you're telling raft that it is safe to discard old log entries.

However, I would echo superfell's comment, that if you don't care about the raft log and the guarantee's it delivers, it may not be a great choice for the problem you are solving. But without knowing your problem space, what your doing may be entirely correct.

**Comment by jonbonazza** [comment]
Thanks everyone for the help and information. I think I properly understand things now and thus will close this issue.
