### ISSUE TITLE
Checking previous log in AppendEntries 

### ISSUE THREAD

**Issue by fahadullah** [hashicorp/raft#205]
I did glance through newer branches but didn't see any change in this behavior. Though I might have missed something. 

In appendEntries(), (https://github.com/hashicorp/raft/blob/master/raft.go#L1375) we check the PrevLogEntry from the leader against the last entry on the follower. But we don't have a guard against the last entry on the follower to be the snapshot. We do similar check on the leader 
(https://github.com/hashicorp/raft/blob/master/replication.go#L458).

If appendEntries() keep returning an error to the leader (e.g. if the logstore is offline), that peer's next index on the leader will keep going back even though the peer has those log entries i.e. last index is higher. Eventually, leader will send a snapshot but all subsequent appendEntries() fail because PrevLogEntry is equal to getLastSnapshotIndex() and there is no log for it.

Shouldn't we attempt to differentiate between "Log Not Found" vs some other error returned from appendEntries()? I believe the retries with decremented index should happen on log inconsistencies only. I was thinking as a quick fix, we can guard against the snapshot index in appendEntries().

Thanks in advance.

**Comment by banks** [comment]
My mistake!
