### ISSUE TITLE
Question: is it possible to force/prioritize a leader assuming stable environment?

### ISSUE THREAD

**Issue by shlomi-noach** [hashicorp/raft#211]
On a raft cluster of, say, 3 nodes, is is possible to _prefer_ a specific one to be the leader?

This may be desirable due to:

- physical location
- machine specs

Is there a way for a node to ask for leadership? Another way?

Thank you.

**Comment by slackpad** [comment]
Hi @shlomi-noach there's currently no way to do this (like a server priority / weight). If you start with just that server in the cluster, let it elect itself, and then add the others after you will end up in that state, but it's not a great solution. Given the randomized nature of elections, it would probably be tricky to add priority to that protocol. If we added something like this it might be cleaner to have the current leader hand ownership over to another healthy server that's higher priority, or something like that.

**Comment by shlomi-noach** [comment]
@slackpad thank you for the explanation!
