### ISSUE TITLE
Is it safe to use the v2 version of this library?

### ISSUE THREAD

**Issue by JelteF** [hashicorp/raft#217]
I'm currently working on a new project involving raft. So I was wondering what the state of the v2 version of this library is for usage in production. I can see on the milestone that there is still some work to do. However, the main thing I'm wondering if there's some things that make v2 more unsafe to use at the moment than v1, because I can see some great improvements in v2.

**Comment by slackpad** [comment]
Hi @JelteF I'd definitely consider https://github.com/hashicorp/raft/tree/library-v2-stage-one stable and usable - Consul and Nomad both ship our releases using that version of the library and have for some time. The https://github.com/hashicorp/raft/tree/library-v2-stage-two is in good shape but we haven't integrated that into our tools yet, so it doesn't have the run time on it yet, at least from HashiCorp. We intend to start integrating that into Consul in the near future.

There are some breaking API changes in v2 (and some small differences in -stage-one vs. -stage-two) so we were holding off taking -stage-one into master so we don't break people twice. Hope that helps!

**Comment by JelteF** [comment]
Hi @slackpad, thanks for the response (sorry that I didn't thank you before). We're now actually at the stage where we want to convert to v2. Would you still recommend using `v2-stage-one` over `v2-stage-two`? Because one of the features I really like from stage-two is the better custom logger support. 

So my question boils down to, is stage-two already being used inside HashiCorp?

**Comment by slackpad** [comment]
> So my question boils down to, is stage-two already being used inside HashiCorp?

Hi @JelteF - not yet. `v2-stage-two` was a pretty significant rewrite and we haven't yet qualified it for any of our products, though we intend to as soon as we can get it onto the roadmap. For the logger we will likely switch that to https://github.com/hashicorp/go-hclog, and that will likely land in `v2-stage-one` some time fairly soon.
