### ISSUE TITLE
Make sure to fsync properly when saving snapshot files 

### ISSUE THREAD

**Issue by preetapan** [hashicorp/raft#229]
[file_snapshot.go](https://github.com/hashicorp/raft/blob/b3d48f1a4e569bc4d4e456e8930e35b1aa996ea7/file_snapshot.go#L387) doesn't explicitly call fsync before close(). This leads to an edge case during machine crashes where the file we renamed doesn't exist on disk.

**Comment by rom-stratoscale** [comment]
For more info: https://groups.google.com/forum/#!msg/consul-tool/8l0WNatZ8N8/Ygjja_DuFwAJ

**Comment by preetapan** [comment]
@slackpad merged to all three branches and updated consul's vendor directory for this
