### ISSUE TITLE
[v2] Rejecting vote request... since we have a leader

### ISSUE THREAD

**Issue by jonbonazza** [hashicorp/raft#235]
I am using the v2-stage-one branch and while everything seems to work fine for the most part, I do have one issue:

I have a cluster of 3 nodes. I take one node down gracefully (used consul as an example of leave/shutdown logic, and waiting for changes to propagate) and the cluster maintains itself at 2 nodes. If I then, however, try to restart the same node (with any combination of ServerID and addr:port), the new node sits there and requests a leader vote forever, with the other two nodes logging ```[WARN] raft: Rejecting vote request from ... since we already have a leader```

I used Consul as an example of the implementation, fwiw.

**Comment by jakelangholz-dv** [comment]
I too am experiencing this exact issue to the 't'.

**Comment by superfell** [comment]
Its sounds like the node thinks its still part of the cluster, if you want to add it back to the cluster you'll need to delete the log on that node and tell the leader to add it as a new peer.

**Comment by ongardie** [comment]
What is the problem? What behavior do you want to see?

**Comment by jonbonazza** [comment]
I am still having major issues with this. I have a cluster of 3 members and If the leader leaves the cluster and then rejoins later, I see the following sequence of events:
```
2017/12/04 19:37:01 [WARN] raft: Heartbeat timeout from "" reached, starting election                                                                                                │2017/12/04 19:41:34 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:01 [INFO] raft: Node at 10.9.141.156:8101 [Candidate] entering Candidate state in term 3                                                                            │2017/12/04 19:41:38 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:01 [DEBUG] raft: Votes needed: 2                                                                                                                                    │2017/12/04 19:41:41 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:01 [DEBUG] raft: Newer term discovered, fallback to follower                                                                                                        │2017/12/04 19:41:45 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:01 [INFO] raft: Node at 10.9.141.156:8101 [Follower] entering Follower state (Leader: "")                                                                           │2017/12/04 19:41:46 [DEBUG] memberlist: Initiating push/pull sync with: 10.9.140.156:8100
2017/12/04 19:37:07 [WARN] raft: Heartbeat timeout from "" reached, starting election                                                                                                │2017/12/04 19:41:49 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:07 [INFO] raft: Node at 10.9.141.156:8101 [Candidate] entering Candidate state in term 5                                                                            │2017/12/04 19:41:55 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:07 [DEBUG] raft: Votes needed: 2                                                                                                                                    │2017/12/04 19:42:00 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:10 [WARN] raft: Election timeout reached, restarting election                                                                                                       │2017/12/04 19:42:05 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:10 [INFO] raft: Node at 10.9.141.156:8101 [Candidate] entering Candidate state in term 6                                                                            │2017/12/04 19:42:09 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:10 [DEBUG] raft: Votes needed: 2                                                                                                                                    │2017/12/04 19:42:14 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:16 [DEBUG] memberlist: TCP connection from=10.9.142.156:58418                                                                                                       │2017/12/04 19:42:16 [DEBUG] memberlist: Initiating push/pull sync with: 10.9.141.156:8100
2017/12/04 19:37:16 [WARN] raft: Election timeout reached, restarting election                                                                                                       │2017/12/04 19:42:18 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:16 [INFO] raft: Node at 10.9.141.156:8101 [Candidate] entering Candidate state in term 7                                                                            │2017/12/04 19:42:21 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:16 [DEBUG] raft: Votes needed: 2                                                                                                                                    │2017/12/04 19:42:27 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:22 [WARN] raft: Election timeout reached, restarting election                                                                                                       │2017/12/04 19:42:32 [WARN] raft: Rejecting vote request from 10.9.141.156:8101 since we have a leader: 10.9.142.156:8101
2017/12/04 19:37:22 [INFO] raft: Node at 10.9.141.156:8101 [Candidate] entering Candidate state in term 8
...
...
...
```
This goes on forever and I have no idea how to solve it. How the heck do you get a node to rejoin an existing cluster?

**Comment by jonbonazza** [comment]
@superfell what makes a node consider itself part of the cluster?

**Comment by jonbonazza** [comment]
FWIW, this only seems to be an issue when the _leader_ leaves and rejoins. if a non-leader leaves and rejoins, it works fine.

**Comment by superfell** [comment]
In v2 the raft log contains the membership details, if you've got a node that you explicitly removed from the cluster, then you'll need to delete its log before you can join it to a cluster. You'll also need to give it a new server ID. 

I'm not sure why you'd remove a node that you were planning to add back in though, what's your use-case for this?

**Comment by jonbonazza** [comment]
@superfell perhaps I am misunderstanding things then. My use case is I want to gracefully shut down a node in the raft cluster, change some config, then bring it back up. Another use case is when doing a rolling restart of the cluster. What's the proper way to gracefully shut down a node so that it can rejoin later?

**Comment by superfell** [comment]
You don't need to do anything specific with the raft library for that, just exit the process and start it back up again. If you're doing a rolling release/restart, remember not to do too many at the same time.

**Comment by jonbonazza** [comment]
Oh, so once a node has an initialized raft.Raft instance, I can just kill the process and everything else will take care of itself?

**Comment by jonbonazza** [comment]
@superfell  So I am able to rejoin now, however on the two nodes that are still alive when the one node goes dow, I see the following repeat indefinitely:
```
2017/12/04 21:53:27 [ERR] raft: Failed to heartbeat to <redacted>:8101: dial tcp <redacted>:8101: getsockopt: connection refused
2017/12/04 21:53:28 [DEBUG] raft: Failed to contact <redacted> in 2m24.557834351s
2017/12/04 21:53:28 [DEBUG] raft: Failed to contact <redacted> in 2m25.044263785s
2017/12/04 21:53:29 [ERR] raft: Failed to AppendEntries to {Voter <redacted> <redacted>:8101}: dial tcp 10.9.140.156:8101: getsockopt: connection refused
2017/12/04 21:53:29 [DEBUG] raft: Failed to contact <redacted> in 2m25.520630936s
2017/12/04 21:53:29 [DEBUG] raft: Failed to contact <redacted> in 2m26.012628627s
```

**Comment by superfell** [comment]
Yeah, that's expected logging from the leader when there's a node it can't reach.

**Comment by jonbonazza** [comment]
@superfell should it ever "give up"?

**Comment by jonbonazza** [comment]
Oh, it's debug logging though. I suppose I can just silence it.

**Comment by JelteF** [comment]
See my PR at https://github.com/hashicorp/raft/pull/256 to see how I've resolved this issue. However, my solution comes with its own downsides. For more details see the this thread on the raft-dev mailing list: https://groups.google.com/forum/m/#!topic/raft-dev/JEtBYaPpHXo

The best solution would be to implement a pre vote rpc, but I think that requires a breaking change in the Transport interface.

**Comment by jonbonazza** [comment]
@superfell  So the situation I am imagining is, say, a cluster of three containerized raft nodes. These containers can be stopped(or die) and a new container started automatically by the orchestration framework. A couple questions in this regard:
1. Should the raft node's ID be ephemeral like a container ID or "sticky" like a specific name?
2. Should the raft state (i.e. the raft.db and snapshots) be maintained across restarts? And if the ID needs to be "sticky", does this raft state need to _always_ be associated with the node of the same ID?

**Comment by jonbonazza** [comment]
ALso, what's the state of the discussion from the link you provided? Seems to have dropped off since end of Oct. It would be really nice to get some sort of official solution implemented.

**Comment by jkassis** [comment]
these are precisely the questions i'm grappling with. i have a three node cluster running in kubernetes. i'm doing application resiliency testing. i manually delete one pod and kubernetes recreates it. the raft log is stored on a persistent volume. so when the node comes up it has some state. kubernetes gives the node a new IP, however, so I'm sending a request to the leader to AddVoter with the old NodeID and the new IP address. the docs say this will update the server address in the cluster logs.  i can't use DNS names because K8S is slow to update DNS when StatefulSets come up. this is a known issue.

**Comment by mrpre** [comment]
@jkassis same scene as me. Do you remember how to join a node with old NodeID + new IP addres + PV log ? I have to delete the log on PV and call remove api to remove this node, then add this node again which means the pv is useless.
