### ISSUE TITLE
Leader Stepdown

### ISSUE THREAD

**Issue by tylertreat** [hashicorp/raft#239]
This might be an unusual case, but I have a situation where I would like to force a leader to step down. Is there any such mechanism to force a leader to move into the follower state? If not, would this be a reasonable addition to the API?

**Comment by tylertreat** [comment]
Looks like this would be solved with #222.

**Comment by preetapan** [comment]
@tylertreat I am closing this out in favor of non voting servers which will become part of master soon. See https://github.com/hashicorp/raft/issues/218#issuecomment-332941998 for more context.
