### ISSUE TITLE
release or tag pls

### ISSUE THREAD

**Issue by doertedev** [hashicorp/raft#240]
Hey there.

Is it possible to do releases or tags here? There are (also somewhat religious +/- political) issues with gopkg.in as the only approach.

Thanks in advance.

**Comment by slackpad** [comment]
Hi @doertedev we plan to do this soon as we are going to tag current master and then merge the library-v2-stage-one branch, which has some breaking changes.

**Comment by TheTincho** [comment]
Adding to this issue, I am trying to update consul in Debian to a newer version (we are still shipping v0.6.4), and I am hitting a wall, as it now depends on the stage-one branch. I should update raft too then (we don't vendor dependencies as a general rule), but I don't know if it is API compatible, and it feels weird to release an unmerged branch..

**Comment by slackpad** [comment]
(from https://groups.google.com/d/msg/raft-dev/fkFWux33Bok/jkV8bN0mBgAJ posted today)

> If you use Hashicorp's golang Raft implementation, we wanted to make you aware of some upcoming changes. 

> We tagged the original stable version of the library that was in master and has been maintained with no breaking API changes as v0.1.0. This was in use by Consul prior to version 0.7.0.

> Early next week, we are planning to merge changes that were staged in the library-v2-stage-one branch, and tag them as v1.0.0. v1.0.0 manages server identities using a UUID, so it introduces some breaking API changes. It also versions the Raft protocol, and requires some special steps when interoperating with Raft servers running older versions of the library. Please see the README for more details on features in v1.0.0 and how to upgrade.

> If you are not doing so already, we recommend vendoring your application's dependency on this library.

> Regards,
> The Consul team at Hashicorp

I'll close this out since the 0.1.0 tag is in place now!
