### ISSUE TITLE
Remove directory fsyncing for windows when saving snapshots 

### ISSUE THREAD

**Issue by preetapan** [hashicorp/raft#241]
Fix for https://github.com/hashicorp/consul/issues/3409 

We call sync on the parent directory to make sure that directory entry edits are also synced to disk. However, this only applies to [unix style file systems](https://en.wikipedia.org/wiki/Inode), and is throwing errors in windows due to known issues with the underlying syscall [FlushFileBuffers](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364439(v=vs.85).aspx)

**Comment by RobbieMcKinstry** [comment]
Hi @preetapan ! It looks like you implemented this about two years ago: https://github.com/hashicorp/raft/blob/master/file_snapshot.go#L410-L427 (`git blame` says you're to thank)
I'm going to close this issue as a result.
