### ISSUE TITLE
Failed to decode incoming command: unknown rpc type 80

### ISSUE THREAD

**Issue by s4ayub** [hashicorp/raft#246]
I was trying out:
(hraftd)[https://github.com/otoolep/hraftd]

Which is a simple implementation of a dist. key value store using hashicorp/raft. When trying to set a key, I received the following error:
```
2017/09/02 17:19:05 [DEBUG] raft-net: :12000 accepted connection from: [::1]:56220
2017/09/02 17:19:05 [ERR] raft-net: Failed to decode incoming command: unknown rpc type 80
```
I was thinking this was an error with the implementation and not hashicorp/raft, but then I tried to make my own simple dist. key value store with a slightly different implementation and I received the same error when making a request to the raft server. 

My methods look like the following: 
``` Go
// Set routes to handle operations on raft servers
rs.router.HandleFunc("/raftkv_set", rs.redirectedSet)
```
---
```Go
// Set sets the value for the given key.
func (rs *RaftStore) Set(key, value string) error {
	m := map[string]string{key: value}

  var b bytes.Buffer
	if err := json.NewEncoder(&b).Encode(m); err != nil {
		return err
	}

	_, err := rs.redirectToLeader(rs.Leader(), "raftkv_set", b)
	return err
}
```
---
```Go
// Redirects the request to the leader
func (rs *RaftStore) redirectToLeader(leader, op string, command bytes.Buffer) ([]byte, error) {
	reply, err := processRequest(fmt.Sprintf("http://%s/%s", rs.RaftServer.Leader(), op), "application/json", &command)
  if err != nil {
		return nil, err
	}

	return reply, nil
}
```
---
**This is where the process messes up, when posting to the server, it doesn't get to the route**
```Go
func processRequest(target string, contentType string, b *bytes.Buffer) ([]byte, error) {
	resp, err := http.Post(target, contentType, b)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	reply, _ := ioutil.ReadAll(resp.Body)
	statusCode := resp.StatusCode
	if statusCode != http.StatusOK {
		return nil, errors.New(string(reply))
	}

	return reply, nil
}
```
---
```Go
// The function that isn't being hit after the post request which applies the command
func (rs *RaftStore) redirectedSet(w http.ResponseWriter, req *http.Request) {
	m := map[string]string{}
	if err := json.NewDecoder(req.Body).Decode(&m); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
  fmt.Println(m)

	c := &command{
		Op:    "set",
		Key:   m["key"],
		Value: m["value"],
	}
	b, err := json.Marshal(c)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	rs.RaftServer.Apply(b, raftTimeout)
}
```

**Comment by otoolep** [comment]
This issue should be closed in favour of https://github.com/otoolep/hraftd/issues/12

**Comment by s4ayub** [comment]
@otoolep Sorry I meant to update the comment with more details but got distracted in doing so, added the details now, should it still be closed? Do you think this is more of an issue with the hraftd implementation than the hashicorp/raft library? 

Any input is appreciated 😄 !

**Comment by s4ayub** [comment]
@otoolep addressed this in hraftd, thank you!

**Comment by superfell** [comment]
It looks like you're trying to make a HTTP POST request [char P is ascii code 80] to the raft transport endpoint on the leader, but the default one is TCP, not HTTP. You'll either need a custom http transport that can host both your service endpoints and the raft requests, or you need a separate listener for the HTTP requests.

**Comment by s4ayub** [comment]
@superfell Interesting, that makes sense. Would you happen to have any examples or resources for building this custom transport layer? Fairly new to this stuff.

**Comment by otoolep** [comment]
[rqlite](https://github.com/rqlite/rqlite) uses this technique to multiplex intra-cluster and Raft communications over the same TCP connection. Check out https://github.com/rqlite/rqlite/tree/master/tcp for the implementation, and check the source code of rqlite to see it in action.
