### ISSUE TITLE
lastSnapshotIndex can go back between InstallSnapshot() and takeSnapshots()

### ISSUE THREAD

**Issue by fahadullah** [hashicorp/raft#248]
Order of operations are,

1. takeSnapshot() runs and receives a copy of snapshot from FSM to persist up to index X. It persists the snapshot but hasn't called setLastSnapshotIndex() yet.
2. InstallSnapshot() runs and restores the FSM to index X + 10 and also sets the lastSnapshotIndex.
3. Now, takeSnapshot() sets lastSnapshotIndex back to X.

Though, followers don't use lastSnapshotIndex for anything critical. It would be bad if it becomes leader, since entries from X to X + 10 are already deleted from the log store.

**Comment by s-christoff** [comment]
Hey @fahadullah, we appreciate this information. 
We are trying to replicate this issue you're having, but having some trouble. Do you have any reproduction steps we can follow, or any scripts that you have that you are currently experiencing this in?

Thanks so much!

**Comment by fahadullah** [comment]
@s-christoff Sorry for the late reply. I might have to dig but I doubt I would be able to find the test I had anytime soon.
