### ISSUE TITLE
Observer enhancements

### ISSUE THREAD

**Issue by james-lawrence** [hashicorp/raft#249]
There are a few events that would be nice to bubble up to the observers. ones I've noticed that would be handy: peers additions/removals, failure to heartbeat, failure to contact. 

is there a particular reason these events are not included? and would this library be open to a PR adding these events?
```
2017/09/23 17:44:47 [ERR] raft: Failed to heartbeat to 127.0.0.1:2002: dial tcp 127.0.0.1:2002: getsockopt: connection refused
2017/09/23 17:44:47 [DEBUG] raft: Failed to contact 127.0.0.1:2002 in 9.787694056s
2017/09/23 17:45:46 [INFO] raft: Added peer 127.0.0.2:2002, starting replication
2017/09/23 17:45:46 [INFO] raft: Removed peer 127.0.0.1:2002, stopping replication (Index: 5)
```

**Comment by freeekanayaka** [comment]
This seems easy and sensible. Any opinion from upstream folks?

**Comment by james-lawrence** [comment]
wish they'd respond I've already implemented patches for myself.

**Comment by RobbieMcKinstry** [comment]
Hello @james-lawrence ! Sorry for the slow reply... we're trying to be more active now!

Would you mind showing me your patch? I suspect these additions would be pretty straightforward. I can't imagine a reason why we wouldn't consider merging (unless it tanks performance by emitting a ton of events).

Thank you!

**Comment by james-lawrence** [comment]
sure i'll see if i can dig this up.

**Comment by RobbieMcKinstry** [comment]
Thank you!

**Comment by RobbieMcKinstry** [comment]
Closed by https://github.com/hashicorp/raft/pull/326
