### ISSUE TITLE
Last node cannot elect itself as a leader

### ISSUE THREAD

**Issue by F21** [hashicorp/raft#260]
I am moving a program from raft v0.1.0 to v1.0.0 and ran into a few problems. I am also using serf master. Serf is used for discovery and raft is used to elect a leader and for consensus.

A sample program is available here: https://gist.github.com/F21/b85ae8af1c6bdb78b4ca0f9d96a89aa0

I am seeing the following problem:
1. Start first node (self-elected as master). `raft-sample -serfPort=1111`
2. Start second node. Serf discovers it and the first node (leader) adds it to raft pool. `raft-sample -serfPort=2222 -members=172.28.128.1:1111`
3. Start third node. Serf discovers it and the first node (leader) adds it to raft pool. `raft-sample -serfPort=3333 -members=172.28.128.1:1111`
4. Kill first node and second node is elected as leader.
5. Kill second node and last node gets stuck in a loop requiring 2 tallies to elect a leader. Since there is only 1 node the leader can't be elected.

Is there anyway to update the known peer list for raft in the last node manually? `AddVoter` and `RemoveServer` requires the node to be a leader in order to work and this creates a catch-22.

**Comment by slackpad** [comment]
Hi @F21 yeah there's no great online way to change it once you get into an outage state. Consul uses the [`RecoverCluster()`](https://github.com/hashicorp/raft/blob/v1.0.0/api.go#L215-L348) API for this situation, which is done at startup to force the state into a configuration with a specific set of peers. Here's how it looks to the user - https://www.consul.io/docs/guides/outage.html#manual-recovery-using-peers-json.

There's no way to force it on the fly (the older library you could update the peer store directly, but it wasn't very robust if you did that), but you can probably build something on top of `RecoverCluster()`. Hope that helps!

**Comment by F21** [comment]
Hey @slackpad, thanks for the tip! I used `RecoverCluster()` and it's almost all the way there.

I have a `time.Ticker` ticking at every 5 seconds to check if there is a leader and whether the last time we contacted a leader is past a certain threshold:

```go
if r.Leader() == "" && time.Since(r.LastContact()) > 10*time.Second {
	fmt.Println("Time to restart!!")

	f := r.Shutdown()

	if f.Error() != nil {
		log.Fatalf("Error shutting down raft: %s", f.Error())
	}

	trans, err := raft.NewTCPTransport(raftAddr, nil, 3, 10*time.Second, os.Stdout)

	fmt.Println("Recovering")
	err = raft.RecoverCluster(c, &fsm{}, raftDB, raftDB, snapshotStore, trans, raft.Configuration{
		Servers: []raft.Server{
			{
				Suffrage: raft.Voter,
				ID:       raft.ServerID(raftAddr),
				Address:  raft.ServerAddress(raftAddr),
			},
		},
	})

	if err != nil {
		log.Fatalf("Error recovering cluster: %s", err)
	}
	fmt.Println("starting new raft")
	r, err = raft.NewRaft(c, &fsm{}, raftDB, raftDB, snapshotStore, trans)

	if err != nil {
		log.Fatal(err)
	}
}
```

The problem is that the restart works correctly, but snapshotting fails at a later point if a node leaves the cluster again.

Here's what happens:
1. Start first node (self-elected as master). raft-sample -serfPort=1111
2. Start second node. Serf discovers it and the first node (leader) adds it to raft pool. raft-sample -serfPort=2222 -members=172.28.128.1:1111
3. Start third node. Serf discovers it and the first node (leader) adds it to raft pool. raft-sample -serfPort=3333 -members=172.28.128.1:1111
4. Kill first node and second node is elected as leader.
5. Kill second node and wait for the there to be no leader and the last leader was contacted more than 10 seconds ago. 
6. Shutdown raft, create new transport, `RecoverCluster()` and create new raft in the third node.
7. Third node becomes the leader.
8. Start up fourth node on a blank slate (no previous raft history).
9. Either the fourth node or third node is elected leader.
10. Kill either the fourth node or the third node.
11. The remaining node will see no leader and once the threshold is met, attempt recovery and restart raft. During `RecoverCluster()`, a snapshot error occurs:

````
017/11/16 10:14:53 [INFO] snapshot: Creating new snapshot at C:\work\rafttest\c8b0beac0a5ee0df18505474cad51749\snapshots\14-9-1510787693498.tmp
2017/11/16 10:14:53 [INFO] snapshot: reaping snapshot C:\work\rafttest\c8b0beac0a5ee0df18505474cad51749\snapshots\5-7-1510787663588
2017/11/16 10:14:53 [ERR] snapshot: Failed to reap snapshot C:\work\rafttest\c8b0beac0a5ee0df18505474cad51749\snapshots\5-7-1510787663588: remove C:\work\rafttest\c8b0beac0a5ee0df18505474cad51749\snapshots\5-7-1510787663588\state.bin: The process cannot access the file because it is being used by another process.
2017/11/16 10:14:53 Error recovering cluster: failed to finalize snapshot: remove C:\work\rafttest\c8b0beac0a5ee0df18505474cad51749\snapshots\5-7-1510787663588\state.bin: The process cannot access the file because it is being used by another process.
```

There does not appear to be a method to shutdown the `FileSnapshotStore`, which I think might be the cause of the problem here.

Any tips?

**Comment by slackpad** [comment]
I don't have time right now to take a deeper look at this but will kick it back open to keep track of it :-)

**Comment by F21** [comment]
I just tested using the `InmemSnapshotStore` and I do not see this problem. This seems to point to a problem within the `FileSnapshotStore`. I'll see if I can investigate further.

**Comment by F21** [comment]
The permission issue seems to be reproducible on Windows only. I cannot reproduce it on linux.

**Comment by F21** [comment]
Going to close this as #262 is more specific
