### ISSUE TITLE
InmemSnapshotStore.Open returns a reader with no content if used twice

### ISSUE THREAD

**Issue by freeekanayaka** [hashicorp/raft#269]
This happens when trying to open the same snapshot a second time. The current code in of InmemSnapshotStore.Open() looks like:

```go
return &m.latest.meta, ioutil.NopCloser(m.latest.contents), nil
```

which means that a second call would get a zero-length reader, since m.latest.contents is a bytes.Buffer that can only be read once, and returns io.EOF the second time.

**Comment by RobbieMcKinstry** [comment]
Thanks for opening this! Good catch!
