### ISSUE TITLE
Are these two arguments related?

### ISSUE THREAD

**Issue by FlyingOnion** [hashicorp/raft#284]
In the function
<pre>
func newTCPTransport(bindAddr string, advertise net.Addr,
transportCreator func(stream StreamLayer) *NetworkTransport) (*NetworkTransport, error)
</pre>
what does the parameter `advertise` use for? If it binds the same address with `bindAddr`, we could use `net.ResolveTCPAddr("tcp", bindAddr)` to get a struct.

**Comment by mkeeler** [comment]
The bindAddr is the address that the socket gets bound to. This could be `0.0.0.0` for example and Raft will listen on all IP addresses.

The advertise address is the address other nodes in the cluster should use to communicate with this node. This address will be advertised to the other nodes when this node joins the cluster. It must not be an ANY address like `0.0.0.0` but a routable address on your network.

**Comment by ozanh** [comment]
Hi, I just wonder that must advertise address be IP:PORT always? In the end, address goes to `net.DialTimeout` which accepts anything resolvable and cluster server configuration can hold host names with port, I guess. Could you please give me a hint? I really like to use advertise addresses as host names.
