### ISSUE TITLE
goroutine error when using the same logger in transport and raft

### ISSUE THREAD

**Issue by FlyingOnion** [hashicorp/raft#287]
This error occurs when I use the same logger in initializing raft. Code like this:
<pre>
func (s *Server) initRaft() error {
	raftConfig := raft.DefaultConfig()
	raftConfig.LocalID = raft.ServerID(s.config.Id)

	// remove this two line and it works well
	raftConfig.Logger = s.logger
	raftConfig.LogOutput = os.Stderr

	// initializing logstore, stablestore, fsm, etc.

	snapshotStore, err = raft.NewFileSnapshotStoreWithLogger(cwd, retainSnapshotCount, s.logger)
	if err != nil {
		return err
	}
	transport, err = raft.NewTCPTransportWithLogger(addr, tcpAddr, tcpMaxPool, 10*time.Second, s.logger)
	if err != nil {
		return err
	}
	s.raft, err := raft.NewRaft(raftConfig, fsm, store, store, snapshotStore, transport)
}

func (s *Server) Start() error {
	if err := s.initRaft(); err != nil {
		return err
	}
	// do other things
}

func NewServer(l log.Logger) *Server {
	return &Server{
		config: c,
		logger: l,
	}
}
</pre>
The function is called like this:
<pre>
logger := log.New("server")
server := NewServer(logger, config)
server.Start()
</pre>
When a node is disconnected, the error occurs:
<pre>
20:21:40.643583 ERR server Failed to make RequestVote RPC to peer id: 002
   address: 127.0.0.1:10087
   error: dial tcp 127.0.0.1:10087: getsockopt: connection refused
goroutine 575 [running]:
runtime/debug.Stack(0x4d19f4, 0xc4201fe005, 0xc4201593f0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/mgutz/logxi/v1.(*HappyDevFormatter).getLevelContext(0xc420154180, 0x3, 0xc42015ade0, 0x0, 0x0, 0x0, 0x0, 0xc4200187a7, 0x5)
	/home/fedora/go/src/github.com/hashicorp/raft/peer.go:794 +0x3e2
github.com/hashicorp/raft.sendHelper(0xc42018e8c0, 0xafd920, 0xc42015cf00)
	/home/fedora/go/src/github.com/hashicorp/raft/peer.go:534 +0x56
github.com/hashicorp/raft.(*peerState).send.func1()
	/home/fedora/go/src/github.com/hashicorp/raft/peer.go:527 +0x3f
github.com/hashicorp/raft.(*waitGroup).spawn.func1(0xc4201582f0, 0xc4201a85e0)
	/home/fedora/go/src/github.com/hashicorp/raft/util.go:122 +0x4f
created by github.com/hashicorp/raft.(*waitGroup).spawn
	/home/fedora/go/src/github.com/hashicorp/raft/util.go:120 +0x62

20:21:40.644190 WRN server
   RPC transport error. Backing off new RPCs for peer (except heartbeats)
   id: 002 address: 127.0.0.1:10087 in: 
20:21:40.644367 ERR server RequestVote error to peer id: 002
   address: 127.0.0.1:10087
   error: dial tcp 127.0.0.1:10087: getsockopt: connection refused
goroutine 20 [running]:
runtime/debug.Stack(0x4d19f4, 0xc420200605, 0xc4201594f0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/mgutz/logxi/v1.(*HappyDevFormatter).getLevelContext(0xc420154180, 0x3, 0xc42015af00, 0x0, 0x0, 0x0, 0x0, 0xc4200187a7, 0x5)
	/home/fedora/go/src/github.com/hashicorp/raft/peer.go:810 +0x21f
github.com/hashicorp/raft.(*peerState).processReply(0xc42016c5a0, 0xafd860, 0xc42015aea0)
	/home/fedora/go/src/github.com/hashicorp/raft/peer.go:560 +0xfb
github.com/hashicorp/raft.(*peerState).blockingSelect(0xc42016c5a0)
	/home/fedora/go/src/github.com/hashicorp/raft/peer.go:446 +0x7e5
github.com/hashicorp/raft.(*peerState).selectLoop(0xc42016c5a0)
	/home/fedora/go/src/github.com/hashicorp/raft/peer.go:415 +0x6f
github.com/hashicorp/raft.(*peerState).(github.com/hashicorp/raft.selectLoop)-fm()
	/home/fedora/go/src/github.com/hashicorp/raft/peer.go:289 +0x2a
github.com/hashicorp/raft.(*waitGroup).spawn.func1(0xc4201582f0, 0xc4201662f0)
	/home/fedora/go/src/github.com/hashicorp/raft/util.go:122 +0x4f
created by github.com/hashicorp/raft.(*waitGroup).spawn
	/home/fedora/go/src/github.com/hashicorp/raft/util.go:120 +0x62
</pre>

**Comment by FlyingOnion** [comment]
I'm using the lib-v2-stage-two branch, where logxi is used. I checked the code and found that `colorableStdout` is concurrent safe, so I wonder the reason of this problem.

**Comment by mkeeler** [comment]
@FlyingOnion Unless I am mistaken its not panicing correct? The mgutz/logxi package looks to emit a callstack in the logs when logging errors.

Could you try running with `LOGXI_FORMAT=context=-1` set in your environment to see if that suppresses the stack trace?

**Comment by mkeeler** [comment]
Actually I am not sure that will prevent the stack trace. Either way the program shouldn't be panicing but rather the trace is a result of using the mgutz/logxi library in that branch

**Comment by mkeeler** [comment]
@FlyingOnion I would advise against using the library-v2-stage-* branches. And this will not occur on master. Therefore I am going to close this.
