### ISSUE TITLE
Library needs more active maintenance.

### ISSUE THREAD

**Issue by james-lawrence** [hashicorp/raft#289]
bunch of useful PR's are just sitting unmerged with no comments from maintainers about when they'll be merged.

its gotten to the point I've been considering having to fork the library and merge them manually to get the benefit of everyones work.

**Comment by pearkes** [comment]
Hey @james-lawrence, definitely a fair point. We've definitely not been able to devote much time recently to getting these useful contributions merged -- but are aware we could do much better and are working on getting more HashiCorp folks involved in a regular (and ongoing) basis. We also intend to continue to invest in substantial improvements to the library based on our experience in using it in Nomad and Consul.

Definitely expect to see more feedback from us in the near future!

**Comment by adampointer** [comment]
I agree. I am on the verge of using a community fork. If someone were to fork and make all these merges I would seriously consider switching to it. Saying that I do feel this would be a backward step in the long term, but it would solve my selfish needs right now.

**Comment by james-lawrence** [comment]
near future has come and passed.

**Comment by freeekanayaka** [comment]
I feel the same as other folks.

@pearkes if at the moment there's no capacity in HashiCorp for maintaining this library, would you consider delegating at least some level of maintenance to some "community" member(s) that you trust?

It feels things are in very good shape already, even without necessarily introducing new features, so even some light maintenance could help a lot with the small paper cuts here and there. For more serious development and enhancements based on experience from Nomad an Consul, of course a broader and deeper requirement of involvement from HashiCorp would be more than understandable.

**Comment by sam3d** [comment]
What I fail to understand is that this is a critical component of both Consul and Nomand, so how is it that this library gets updated so irregularly when it's such a fundamental puzzle piece of these two "enterprise-ready" tools?

**Comment by freeekanayaka** [comment]
@sam3d my explanation is that it works fine enough for the two projects you mentioned. Let's keep in mind that this lib went through several development iterations, so I guess it got stable enough for their use.

**Comment by freeekanayaka** [comment]
My impression is that the paper cuts are clearly not important enough to them to justify further work. Of course this an explanation, not a justification. Regarding the 4 months with no maintainer activity, that's not a bad fact by itself (if a piece of code works, does not need need new features and doesn't regress with respect to its dependencies, then it's fine), but of course a bit more love would be nice.

Personally I needed to transition my Raft-based project from Go to C, so I've started a Raft library in C (since there is none that did what I wanted), so I'm not concerned much anymore about hashicorp/raft. See [here](https://github.com/CanonicalLtd/raft) if curious, still wip.

**Comment by RobbieMcKinstry** [comment]
Hi! Thanks for the input. We've put together a group internally to perform more active maintenance. We intend to increase our activity on this package.

However, that doesn't mean we'll necessarily merge all of the outstanding, useful PRs. I wish it were so! All of our enterprise products rely on Raft. This means that any change we made has high impact -- and thus comes with high risk. We have to devote some time to code review and testing before we can merge our PR. Now that we've got some extra hands on deck to help with maintenance of this library, I suspect that we'll dig into the backlog of PRs soonish.

**Comment by sam3d** [comment]
Thank you for the update @RobbieMcKinstry, exciting news! I think I speak for a lot of us when I say that we're not looking for massive changes; I can honestly say that having some confirmation of continued active maintenance is reassurance enough for our team to continue investing in this incredibly useful library.

**Comment by RobbieMcKinstry** [comment]
Glad to hear it @sam3d Thank you and your team for investing in OSS!
