### ISSUE TITLE
a question about apply logs in candidate node

### ISSUE THREAD

**Issue by GitRainy** [hashicorp/raft#297]
i try to apply log in a candidate node, i know it must redirect to leader then execute,but i don't hope achieve this through http. In fact, i only hope i can  achieve this through communication between its own clusters, but i don't how to do it,can you give me some ideas? thanks

**Comment by i0rek** [comment]
Hi @GitRainy, thanks for asking! Could you try to describe you issue and your setup more detailed? Right now I don't understand what you are trying to do. Thanks!
