### ISSUE TITLE
Obtaining peers before starting Raft processing

### ISSUE THREAD

**Issue by stapelberg** [hashicorp/raft#298]
In RobustIRC (which I’m trying to migrate from raft v0 to raft v1), we verify that the clock of the node which is about to join the network is synchronized (well enough) with the remaining nodes: https://github.com/robustirc/robustirc/blob/38fd78c7f0b39fe25a78d33805b89b26617363c3/robustirc.go#L398-L417

This ensures that accidental clock drift doesn’t e.g. expire all active sessions or prevent new messages from being accepted due to incorrect throttling state.

To verify the clocks, the node needs to know the server addresses of the other nodes in the network *before starting Raft processing*. Up until now, we have used raft.NewJSONPeers, but that no longer exists. I can’t see an exported function yet for obtaining the configuration from the combination of snapshot+log.

How can callers accurately obtain the most recent configuration? If there is no way currently, would you accept a PR which adds such a function?

Thanks!

**Comment by RobbieMcKinstry** [comment]
Hi @stapelberg ! We would accept a PR. Would you mind explaining your approach to implementing your PR?

We suspect the best way to implement this is to add a function which starts an instance which reads its local state from disk, but doesn't start talking to peers yet.

Another approach, for your use case, might be to start each node individually and write the timestamps to the log for the other nodes to independently verify. Maybe this isn't appropriate if you don't want the nodes participating in the cluster at all until they've verified the timestamps. Maybe you could add the new nodes as nonvoting servers until they verify their time? Your suggestion is still reasonable, without a doubt.
