### ISSUE TITLE
cannot take snapshot

### ISSUE THREAD

**Issue by nnsgmsone** [hashicorp/raft#318]
I found that the newly added node will repeatedly create a snapshot. Why?

![2019-04-18 10-32-43 的屏幕截图](https://user-images.githubusercontent.com/31609524/56333150-8d626c00-61c5-11e9-8072-d3c792eaf672.png)
log is above

**Comment by nnsgmsone** [comment]
The current situation seems to be that the new node has processed the log, but the commit index has not increased.

**Comment by nnsgmsone** [comment]
the lastindex in function runFSM  is  less than idx in fucntion appenEntries，Below is the code and the log output:
![2019-04-18 18-11-28 的屏幕截图](https://user-images.githubusercontent.com/31609524/56354058-6deb3380-6205-11e9-8b56-61dfe04c6a9b.png)
![2019-04-18 18-04-10 的屏幕截图](https://user-images.githubusercontent.com/31609524/56354060-6fb4f700-6205-11e9-90a2-be3856a1d423.png)
The value of commit index is 12，below is the log:
![2019-04-18 18-10-06 的屏幕截图](https://user-images.githubusercontent.com/31609524/56354080-7cd1e600-6205-11e9-96f9-8160274230ef.png)
But index is only 11, obviously all the logs have been executed, but only 11.
![2019-04-18 18-11-13 的屏幕截图](https://user-images.githubusercontent.com/31609524/56354298-efdb5c80-6205-11e9-9ac7-8549600170db.png)

**Comment by nnsgmsone** [comment]
First of all, I added the following log in code:

![2019-04-18 18-20-50 的屏幕截图](https://user-images.githubusercontent.com/31609524/56354588-ba833e80-6206-11e9-8d3b-caec37f6271e.png)
Then I run two nodes, and add a node after processing some data, the following error will occur:
![2019-04-18 18-23-47 的屏幕截图](https://user-images.githubusercontent.com/31609524/56354738-1fd72f80-6207-11e9-993f-cbce3e03f768.png)
![2019-04-18 18-24-16 的屏幕截图](https://user-images.githubusercontent.com/31609524/56354775-341b2c80-6207-11e9-867f-0f470232ee94.png)
![2019-04-18 18-24-43 的屏幕截图](https://user-images.githubusercontent.com/31609524/56354803-42694880-6207-11e9-91fe-5bd04c572b76.png)
it seems enter an infinite loop. How can I fix this bug?

**Comment by nnsgmsone** [comment]
I found that the cause of this problem is because only logs of type LogCommand will update lastindex:
![2019-04-19 10-32-29 的屏幕截图](https://user-images.githubusercontent.com/31609524/56403534-5313d000-6294-11e9-8a65-538a0689bdf7.png)
So the commitindex is updated, but lastindex is not updated.So it will always enter the following process, leading to an infinite loop:
![2019-04-19 11-15-59 的屏幕截图](https://user-images.githubusercontent.com/31609524/56403588-95d5a800-6294-11e9-8319-3e8eb4b430ef.png)

**Comment by nnsgmsone** [comment]
I think you can check the snapReq.index and commitIndex before calling the user callback. Why not?Is there any special consideration?

**Comment by s-christoff** [comment]
Hey @nnsgmsone, thank you so much for all this information. Are you able to push up your code into a repository so we can take a deeper look into it? I feel like it would help give us a lot of additional context. 
Thank you!

**Comment by nnsgmsone** [comment]
Ok, I will write a simple  example and send it to you

**Comment by nnsgmsone** [comment]
@s-christoff the repository is https://github.com/nnsgmsone/raft_test.git。My step is to start two nodes first, then call the client to send the request, wait for the snapshot to be created. then start a new node, and then you will see the situation.

**Comment by james-lawrence** [comment]
for the record I've seen this as well in our production system.

**Comment by nnsgmsone** [comment]
@james-lawrence how do you deal with this problem?
