### ISSUE TITLE
Why does config.SnapshotInterval exist?

### ISSUE THREAD

**Issue by stapelberg** [hashicorp/raft#32]
Given that we have `config.SnapshotThreshold`, I don’t see why the snapshot interval is configurable. Could we not set it to 1s fixed (as an example)? Given that `shouldSnapshot()` only does two reads (to get the last snapshot index from stablestore and the last log index from logstore), I don’t think it’s too expensive to do once a second…?

Could you please explain the rationale behind this or confirm my understanding, in which case I’ll send a cleanup pull request?

**Comment by armon** [comment]
Doing the check is relatively cheap, but the actual snapshot itself is generally not. It usually requires serializing all memory state to disk, which you'd rather not do every second.

**Comment by stapelberg** [comment]
Agreed. But I still think it’s weird that there are two tunables (`SnapshotInterval` and `SnapshotThreshold`).

For a snapshot to happen every second, at least `config.SnapshotThreshold` (defaulting to 8192) raft log entries will need to have been written each second, which is not realistic based on the performance I observe with raft (what’s the typical throughput you see with consul?).

If snapshots are happening too often, why not just increase `SnapshotThreshold`? That way, the user acknowledges what the downside of not having frequent snapshots are, i.e. more logs to replay.

At least in my application, I’d like to ensure snapshots happen often so that there is some pressure to implement them in a non-blocking/fast way. With infrequent snapshots, users would see a dip in throughput every `SnapshotInterval`. With frequent snapshots, throughput would naturally be limited to a number that is sustainable, even during snapshots. I prefer the latter for consistent long-term performance.

**Comment by armon** [comment]
Because they are both tunable, you can change them to fit your needs! You could always set a very low threshold and interval to get what you want. For systems like Consul, we want to strike a balance between not snapshotting very often, and also avoiding a snapshot when it's relatively fast to just replay the last 8K updates.

In practice, we can get 4-5K updates per second at peak, but generally traffic is much lower.
