### ISSUE TITLE
Faild to start when in docker

### ISSUE THREAD

**Issue by inewlife** [hashicorp/raft#343]
[store] 2019/07/01 19:12:01 node node2 at 10.42.241.237:11002 joined successfully
2019/7/1 下午7:12:01panic: runtime error: invalid memory address or nil pointer dereference
2019/7/1 下午7:12:01[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804a40b]
2019/7/1 下午7:12:01
2019/7/1 下午7:12:01goroutine 16328 [running]:
2019/7/1 下午7:12:01runtime/internal/atomic.Load64(0x9ce4c2c, 0x9ed43a0, 0x0)
2019/7/1 下午7:12:01	/usr/local/go/src/runtime/internal/atomic/asm_386.s:194 +0xb
2019/7/1 下午7:12:01gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft.(*Raft).replicateTo(0x9e34000, 0x9ce4c00, 0x4, 0x0, 0x0)
2019/7/1 下午7:12:01	/go/src/gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft/replication.go:205 +0xa6
2019/7/1 下午7:12:01gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft.(*Raft).replicate(0x9e34000, 0x9ce4c00)
2019/7/1 下午7:12:01	/go/src/gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft/replication.go:154 +0x3b9
2019/7/1 下午7:12:01gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft.(*Raft).startStopReplication.func1()
2019/7/1 下午7:12:01	/go/src/gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft/raft.go:488 +0x27
2019/7/1 下午7:12:01gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0x9e34000, 0x17e42910)
2019/7/1 下午7:12:01	/go/src/gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft/state.go:146 +0x44
2019/7/1 下午7:12:01created by gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft.(*raftState).goFunc
2019/7/1 下午7:12:01	/go/src/gitlab.gz.cvte.cn/dp/go_cache/vendor/github.com/hashicorp/raft/state.go:144 +0x54

**Comment by s-christoff** [comment]
Hey @inewlife , thank you so much for bringing this to our attention. Could you provide us with in depth replications steps and/or a Github repository with any code you may be running or using?

**Comment by banks** [comment]
This looks like an issue with unaligned 64-bit atomic instructions on a 32-bit build. We should audit atomics and fix struct alignment.

**Comment by inewlife** [comment]
> This looks like an issue with unaligned 64-bit atomic instructions on a 32-bit build. We should audit atomics and fix struct alignment.
Thanks,tried again, but it was still no go

**Comment by inewlife** [comment]
@banks Thanks,tried again, but that does not work

**Comment by inewlife** [comment]
@banks Thank you very much,it's work now
