### ISSUE TITLE
fuzzy: Unable to run fuzzy test

### ISSUE THREAD

**Issue by nilsocket** [hashicorp/raft#352]
Unable to run tests under fuzzy folder.

It's a build error

I tried by checking out to v1.1.0, even there it is failing.

Thank you.

**Comment by catsby** [comment]
I opened a PR for this here: https://github.com/hashicorp/raft/pull/363

Unfortunately I don't know for absolute certain that it fixes the issues that @nilsocket  experienced, there are some missing details on the specifics but at least with that change they tests compile, run, and pass.

**Comment by nilsocket** [comment]
@catsby , I think I just ran `go test` in that directory, I think it's safe to close this issue, if you have fixed it.

Thank you.

**Comment by catsby** [comment]
@nilsocket awesome, thanks. It should get closed automatically when #363 is merged
