### ISSUE TITLE
Snapshot can attempt to delete a negative range from log

### ISSUE THREAD

**Issue by banks** [hashicorp/raft#358]
Debugging something in consul I noticed raft log messages like this:

```
raft: Compacting logs from 26108 to 6079
```

Looking at https://github.com/hashicorp/raft/blob/ff523e1c1515a5b33cc3153a34c984093fed06bb/snapshot.go#L231-L235

This is in fact the min/max values we are passing to `DeleteRange` on the log store.

Our `LogStore` interface doesn't define what the behaviour should from implementations in that case although our `raft-boltdb` store that we use everywhere happens to make that a no-op so it's not causing actual issue other than a confusing log message.

I suggest we  add a bounds check just before those lines to verify that max is strictly larger than min and if not just return possibly with a nice log like "no logs to truncate".

**Comment by jscode017** [comment]
Are anyone on this one?
If not may I take this as my first issue?

**Comment by banks** [comment]
Please do take it! Thanks for contributing!

**Comment by catsby** [comment]
https://github.com/hashicorp/raft/pull/362 was opened, thanks @jscode017 :D

**Comment by banks** [comment]
Thanks @dineshba good spot.
