### ISSUE TITLE
linearizable read

### ISSUE THREAD

**Issue by nnsgmsone** [hashicorp/raft#359]
Does the library provide any linearizable read strategy?

**Comment by RobbieMcKinstry** [comment]
Technically it does. Consul (which uses Raft) allows a "consistency mode" which makes use of linearized reads. [Here's](https://github.com/hashicorp/consul/blob/89158c7a7665a48735ecf8541b72c83c860fe195/agent/consul/rpc.go#L524)
how Consul does it 
The request has to go through the leader, and the leader will do a read from in memory. Then it has to contact a quorum and ensure that it's still the leader. That guarantees the read isn't stale.

You can do this by having the leader call `(raft *Raft) VerifyLeader()`.

**Comment by RobbieMcKinstry** [comment]
Hope that helps! Please let me know if you have any more questions!

**Comment by RobbieMcKinstry** [comment]
Another subtly: the leader has to get passed its write barrier: it has to have finished applying committed logs to it's FSM before it can proceed.

**Comment by nnsgmsone** [comment]
@RobbieMcKinstry ok, Even accessing the leader will access dirty data. . . . At this point, maybe i need the technology of ReadIndex...
