### ISSUE TITLE
Typed ErrKeyNotFound breaks raft-boltdb and raft interoperability

### ISSUE THREAD

**Issue by otoolep** [hashicorp/raft#378]
Unless I am missing something, I believe that https://github.com/hashicorp/raft/pull/370 prevents top-of-tree  https://github.com/hashicorp/raft-boltdb and top-of-tree https://github.com/hashicorp/raft working together. 

The following code, for example, breaks:
```
	// Create the log store and stable store.
	logStore, err := raftboltdb.NewBoltStore(filepath.Join(s.raftDir, "raft.db"))
	if err != nil {
		return fmt.Errorf("new bolt store: %s", err)
	}

	cacheStore, err := raft.NewLogCache(512, logStore)
	if err != nil {
		return err
	}

	var log raft.LogStore
	log = cacheStore
	var stable raft.StableStore
	stable = logStore

	// Instantiate the Raft system.
	ra, err := raft.NewRaft(config, s, log, stable, snapshots, transport)
	if err != nil {
		return fmt.Errorf("new raft: %s", err)
	}
```
with an error such as `new raft: failed to load current term: not found`.

This is because this change meant `ErrKeyNotFound` errors are no longer the same types, which means this `if` clause is never true: https://github.com/hashicorp/raft/blob/master/api.go#L464

This may not be seen in this repo because if testing is done with the in-memory store, BoltDB is not used. Furthermore Consul vendors Raft, and is not yet picking up this change.

https://github.com/hashicorp/raft/pull/370 should probably be reverted. 

cc @programmer04 cc @catsby

**Comment by otoolep** [comment]
You can see this on Circle, in my own project [rqlite](https://github.com/rqlite/rqlite/tree/hashicorp_v1): https://circleci.com/gh/rqlite/rqlite/2724

Again, perhaps I am missing something.

**Comment by otoolep** [comment]
Or both the raft package and the raft-boltdb package should use the same error. The error might have to be defined independently like, say, `io.EOF`, and imported by both.

**Comment by i0rek** [comment]
Thanks for reporting, I will check that.

**Comment by catsby** [comment]
Hey @otoolep - thanks for reporting this. I've opened https://github.com/hashicorp/raft/pull/382 to revert #370, sorry for the delay!

**Comment by catsby** [comment]
@otoolep 

> Or both the raft package and the raft-boltdb package should use the same error. The error might have to be defined independently like, say, io.EOF, and imported by both.

I think this is the right path forward, I'll look around for other examples in the code to see if there's a common errors package and if not, if there could be.

**Comment by catsby** [comment]
#382 was merged. I'm going to close this issue for now, but let us know if it needs to be reopened for any reason. Thanks again!
