### ISSUE TITLE
Get unavailable nodes from the leader?

### ISSUE THREAD

**Issue by ickby** [hashicorp/raft#401]
Currently the API does not support to get feedback on the state of nodes in the cluster. With the hearbeats send by the followers there should be a way to detect missing nodes by the leader, and that quite fast. It would be interesting to get this information, maybe in the observer. Do I overlook a possibility to get the info, or could this be added if not?

I want to implement auto-manage of a cluster, which removes nodes if they are not working anymore. But I need way to detect nodes failing, and it seems counter intuitive to add an additional heartbeat next to rafts one.

**Comment by Wicked7000** [comment]
Just as an additional bump I'm also looking for this behaviour, currently when a node fails the cluster constantly keeps pinging it (When after X amount of time I'd just like to remove it from the cluster). It seems as though this information used to be available via PeerStore but no longer is?

**Comment by szab100** [comment]
bump! this is quite important, I'd like to do the same, monitor missing nodes and auto-remove them.. this way I can have a stateless replicaSet/deployment with an init script that takes the headless service's DNS hostname that resolves to all active pods, iterate over them, find the first leader and join as follower ==> zeroconf auto cluster grouping.. But this cannot work properly without auto-removal..

**Comment by ickby** [comment]
Resolved by #405. Thanks!
