### ISSUE TITLE
tcp_transport doesn't fail when advertise address has no IP

### ISSUE THREAD

**Issue by shou1dwe** [hashicorp/raft#402]
I believe this check is not sufficient for the intention:
https://github.com/hashicorp/raft/blob/master/tcp_transport.go#L84
```golang
if addr.IP.IsUnspecified() {
	list.Close()
	return nil, errNotAdvertisable
}
```

consider this code:
```golang
addr, _ = net.ResolveTCPAddr("tcp", ":12322")
fmt.Println("%v \n", addr.IP)
fmt.Println("%v \n", addr.IP.IsUnspecified())
```
Output:
```
<nil>
false
```

Since binding to `":12322"` or `"0.0.0.0:12322"` is technically the same, I think a `nil` check in the above if condition is necessary to enforce the intention.

**Comment by s-christoff** [comment]
Resolved, thank you so much! :)
