### ISSUE TITLE
Build label indicates that the build is failed

### ISSUE THREAD

**Issue by alwindoss** [hashicorp/raft#406]
The build label indicates that the build has failed. On clicking it I am taken to travis-ci page which says this is not an active project.

Does this label require any update to indicate the right build status?

**Comment by alwindoss** [comment]
@s-christoff if you could share details of the CircleCI I can remove the existing badge and may be replace it with the CircleCI badge

**Comment by s-christoff** [comment]
It looks like for me the CircleCI badge is already added right next to the Travis badge. So all that needs to be done is the Travis badge needs removed! :)

**Comment by alwindoss** [comment]
Thanks I will raise a PR soon.

**Comment by alwindoss** [comment]
@s-christoff Fixed it in PR https://github.com/hashicorp/raft/pull/407

**Comment by alwindoss** [comment]
Can this be closed?

**Comment by s-christoff** [comment]
Yep! On it - sorry about that. :)
