### ISSUE TITLE
why increase term immediately？

### ISSUE THREAD

**Issue by lee3164** [hashicorp/raft#411]
https://github.com/hashicorp/raft/blob/ae3f4f2e0ae5e88dab8c9f6dc2521a45121f9a2a/raft.go#L1431

if a node disconnect from cluster and others works well, this node will increment its term and request vote. when this node connect to the cluster again. the term will be greater than others. if this time lost leader and this node become an candidate will increase others term too.

**Comment by vision9527** [comment]
Yeah you are right, it's need to add an optimization here. It's not necessary for original implement of raft.

**Comment by s-christoff** [comment]
Howdy @lee3164,
I'm a bit confused by the code you are referencing, do you intend to [reference this piece here](https://github.com/hashicorp/raft/blob/a3fb4581fb07b16ecf1c3361580d4bdb17de9d98/raft.go#L1374-L1379)?
What you are describing is a problem covered by [Diego's Thesis under Section 4.2.3 Disruptive Servers](https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf). The proposed solution follows:
```
We modify the RequestVote RPC to achieve this: if a server receives a RequestVote
request within the minimum election timeout of hearing from a current leader, it does not update its
term or grant its vote. It can either drop the request, reply with a vote denial, or delay the request;
the result is essentially the same. This does not affect normal elections, where each server waits at
least a minimum election timeout before starting an election. However, it helps avoid disruptions
from servers not in Cnew: while a leader is able to get heartbeats to its cluster, it will not be deposed
by larger term numbers
```

PRs are definitely welcome for this improvement!

**Comment by vision9527** [comment]
https://github.com/hashicorp/raft/issues/31

**Comment by lee3164** [comment]
yes, pre-vote is a solution here, etcd has implemented this feature. but I think hashicorp/raft is more readable than etcd/raft

**Comment by ncabatoff** [comment]
Closing this as a dup of #31.
