### ISSUE TITLE
Raft warnings failed to contact

### ISSUE THREAD

**Issue by jfr85** [hashicorp/raft#435]
Hi,

I have posted a question about this on stackoverflow:
[raft-connection-timeouts](https://stackoverflow.com/questions/64971903/raft-connection-timeouts)

(I don't want to cross-post).
Please check it out, I can use any feedback.
Thanks in advance.

**Comment by s-christoff** [comment]
Howdy @jfr85, thank you for bringing this to our attention. However I feel this would benefit from being submitted to [RQlite](https://github.com/rqlite/rqlite). Have a happy new year!
