### ISSUE TITLE
Support CheckQuourm optimization

### ISSUE THREAD

**Issue by komuw** [hashicorp/raft#436]
Require leaders to actively step down if they do not receive AppendEntries responses from a majority of servers. 

See section 6.2 of Ongaro’s thesis[1]. Also see[2][3]

1. https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf
2. https://decentralizedthoughts.github.io/2020-12-12-raft-liveness-full-omission/
3. https://github.com/etcd-io/etcd/issues/3866

**Comment by thrawn01** [comment]
I believe this is already implemented here: https://github.com/hashicorp/raft/blob/e3c5b666287bb8dfe4131ae8759eacc75bbb39c0/raft.go#L903-L909

**Comment by komuw** [comment]
> I believe this is already implemented here:
> 
> https://github.com/hashicorp/raft/blob/e3c5b666287bb8dfe4131ae8759eacc75bbb39c0/raft.go#L903-L909

Thanks for the reference.
