### ISSUE TITLE
Difference between commit Index condition in official paper and implementation

### ISSUE THREAD

**Issue by hqt** [hashicorp/raft#440]
I read the [official Raft paper](https://raft.github.io/raft.pdf) for the condition to update the `commitIndex` at the leader

```
If there exists an N such that N > commitIndex, a majority of matchIndex[i] ≥ N, and log[N].term == currentTerm: set commitIndex = N
```

The main point here is: We must have the condition `log[N].term == currentTerm`, otherwise, there is a situation mentioned in the paper that we might have an issue

<img width="480" alt="Screenshot 2021-02-15 at 2 59 16 AM" src="https://user-images.githubusercontent.com/1527614/107886291-d73f4900-6f39-11eb-9354-6c487afc3886.png">

When I read the source code [here](https://github.com/hashicorp/raft/blob/master/commitment.go#L85), however it seems the condition isn't there. Can someone point me some light about this?

**Comment by s-christoff** [comment]
Howdy @hqt,
Thank you for this question! Well spotted, we had to think about this for a bit to see if it was correct.
First, a [new commitment object](https://github.com/hashicorp/raft/blob/main/commitment.go#L26) is started each time a new leader is elected and a new term is started. With this, a new [StartIndex](https://github.com/hashicorp/raft/blob/main/commitment.go#L20) is created which is the first index within that term. This means according to this statement, no entries that are less than the StartIndex will be considered committed. https://github.com/hashicorp/raft/blob/f7242e76aa8944d87eceda619705c3ac208b8aef/commitment.go#L97-L99

The leader will only call Match() will only call once it has written the log to its own disk, and when it has received an acknowledgement from a follower for the AppendEntries RPC. Which means it knows that the log was committed to a quorum of nodes during its leadership term. 
https://github.com/hashicorp/raft/blob/f7242e76aa8944d87eceda619705c3ac208b8aef/replication.go#L603-L613

I hope this answers your question :)
