### ISSUE TITLE
question: The meaning of LogStore#Last/First?

### ISSUE THREAD

**Issue by sleagon** [hashicorp/raft#448]
Is it necessary to keep Log instance in order? The index of last Log instance may not be the biggest.

**Comment by s-christoff** [comment]
Howdy @sleagon,
As far as the [Raft: In Search of an Understandable Consensus Algorithm](https://raft.github.io/raft.pdf) goes it assumes that the logs are in order by term (sequentially) to help against leadership failures and keep the log consistent. 
To clarify any potential confusions, when we say `first` in our implementation it is the oldest one (first one that was written that still exists) and when we say `last` it is the most recent one (latest update)
Let me know if you have any other questions or this was not what you were looking for :)
