### ISSUE TITLE
why SnapshotThreshold smalll than trailinglogs?

### ISSUE THREAD

**Issue by zdyj3170101136** [hashicorp/raft#470]
SnapshotThreshold default condig is 8192.

trailinglogs default config is 10240.

if we have 9000 logs now, we will try make snapshot, and beacusr of 9000 < 10240,we will not delete logs.

if we have 10241 logs now, we will try make snapshot, and because 10241 - 10240 = 1, we will delete 1 log.

so why SnapshotThreshold smalll than trailinglogs?

**Comment by ncabatoff** [comment]
Hi @zdyj3170101136,

Good question.  I don't have a good answer, these values were set many years before I ever worked on Raft.  Note however that these config options are pretty orthogonal, though somewhat related - in that one is about when snapshots happen, and the other is about what to do after a snapshot.  So long as they achieve their goals of ensuring that snapshots happen at a good frequency, I wouldn't worry too much about how they relate to one another.

What is your concern about SnapshotThreshold being smaller than TrailingLogs?
