### ISSUE TITLE
 joint consensus？ or  single step changes?

### ISSUE THREAD

**Issue by xylophonee** [hashicorp/raft#481]
Does Membership Changes use joint consensus or single step changes?

**Comment by woodliu** [comment]
Anyone can answer the question, i am also curious about this

**Comment by woodliu** [comment]
> https://raft.github.io/raft.pdf

Thank you for replying, according to this [MR](https://github.com/hashicorp/raft/issues/16), the hashicorp/raft only support _single step changes_, as it has been 10 years, i am not sure if it implements the _Joint consensus_ ...
