### ISSUE TITLE
Option for NonLeader

### ISSUE THREAD

**Issue by saschamonteiro** [hashicorp/raft#495]
I have a requirement to have 3 servers, but only 2 of them are allowed to become a leader, could this be achieved?

**Comment by i0rek** [comment]
You can configure a server as `NonVoter`: https://github.com/hashicorp/raft/blob/ba088691dde22d4268e302005370d8cd1eea99d1/configuration.go#L15. This is not exactly what you want, but maybe it helps. NonVoters receive logs, don't vote in elections and never become a leader themselfes.

**Comment by saschamonteiro** [comment]
thanks @i0rek , yeah that doesn't quite help, I need an elector/voter only, like some other systems have as option, I tried calling LeadershipTransfer from the instance I don't want to become leader, but times out if one of the other 2 servers is offline
