### ISSUE TITLE
I have a question to ask

### ISSUE THREAD

**Issue by yemingfeng** [hashicorp/raft#497]
Hello, I have a project to build distributed KV storage with grpc + pebble.
The master-slave replication function of hashcorp/raft is used.
But after testing, I found that the performance is only 200QPS.
There may be something wrong with the way I use it. But I would like to ask what is the benchmark result of the master-slave data replication scenario of hashcorp/hash?
Thanks a lot.

**Comment by ncabatoff** [comment]
Apologies we didn't answer this sooner.  In general, benchmarking will be very dependent on various factors such as the hardware used, so we're not going to be able to provide specific numbers.  I hope your project was educational.
