### ISSUE TITLE
seeing lots of DuplicateVotes and elections with no outcome

### ISSUE THREAD

**Issue by superfell** [hashicorp/raft#50]
I'm seeing issues where if i start 3 nodes at the same time (e.g. all on the same host using goreman or similar), it takes a long time to get to an election that actually elects a leader, i see this pattern repeated

10:12:26 n3 | 2015/07/22 10:12:26 [WARN] raft: Election timeout reached, restarting election
10:12:26 n3 | 2015/07/22 10:12:26 [INFO] raft: Node at 127.0.0.1:5003 [Candidate] entering Candidate state
10:12:26 n1 | 2015/07/22 10:12:26 [WARN] raft: Election timeout reached, restarting election
10:12:26 n1 | 2015/07/22 10:12:26 [INFO] raft: Node at 127.0.0.1:5001 [Candidate] entering Candidate state
10:12:26 n2 | 2015/07/22 10:12:26 [WARN] raft: Election timeout reached, restarting election
10:12:26 n2 | 2015/07/22 10:12:26 [INFO] raft: Node at 127.0.0.1:5002 [Candidate] entering Candidate state
10:12:26 n1 | 2015/07/22 10:12:26 [DEBUG] raft: Votes needed: 2
10:12:26 n1 | 2015/07/22 10:12:26 [DEBUG] raft: Vote granted. Tally: 1
10:12:26 n3 | 2015/07/22 10:12:26 [DEBUG] raft: Votes needed: 2
10:12:26 n3 | 2015/07/22 10:12:26 [DEBUG] raft: Vote granted. Tally: 1
10:12:26 n3 | 2015/07/22 10:12:26 [INFO] raft: Duplicate RequestVote for same term: 77
10:12:26 n1 | 2015/07/22 10:12:26 [INFO] raft: Duplicate RequestVote for same term: 77
10:12:26 n2 | 2015/07/22 10:12:26 [DEBUG] raft: Votes needed: 2
10:12:26 n2 | 2015/07/22 10:12:26 [DEBUG] raft: Vote granted. Tally: 1
10:12:26 n1 | 2015/07/22 10:12:26 [INFO] raft: Duplicate RequestVote for same term: 77
10:12:26 n3 | 2015/07/22 10:12:26 [INFO] raft: Duplicate RequestVote for same term: 77
10:12:26 n2 | 2015/07/22 10:12:26 [INFO] raft: Duplicate RequestVote for same term: 77
10:12:26 n2 | 2015/07/22 10:12:26 [INFO] raft: Duplicate RequestVote for same term: 77
10:12:28 n3 | 2015/07/22 10:12:28 [WARN] raft: Election timeout reached, restarting election

This pattern repeated for 40 terms before it was finally able to pick a leader.

I was able to repro this with a simple 3 node config/wrapper with the bolt store and  a no-op FSM. see this for the code.
https://gist.github.com/superfell/1c8f81df0ccd955ed3fb

This uses the default config as returned by raft.DefaultConfig(), perhaps there's not enough variability in the election timeout?

**Comment by superfell** [comment]
Dug into this a little more, the randomization for the election timeout (and other timeouts) is via math/rand, which uses a deterministic seed (each run of the process will see the same sequence of random values), so the timeout is randomized, but the randomized values are moving in lock step in each node.

Seems like this should create a new source that's seeded by something derived from the node, like the listen address to make each nodes randomization different. [If that seems reasonable, i'd be happy to code it up and submit a PR]

**Comment by armon** [comment]
@superfell We should maybe just pull in some real entropy (crypto/rand) and seed math/rand as a simpler approach.

**Comment by superfell** [comment]
That'll work too, i didn't know if anything was relying on it being deterministic (perhaps tests)
