### ISSUE TITLE
Node reapplies logs on every restart

### ISSUE THREAD

**Issue by kotyara85** [hashicorp/raft#523]
Hello,
Every time a new restarts it will receive all log from the leader, is that an expected behavior?
I'd expect only replication for missing data instead of full log
Thank you

**Comment by 838239178** [comment]
I met this problem too

**Comment by 838239178** [comment]
I notice that configuration last index never changed.

I try to remove a follower：

`DemoteVoter(raft.ServerID(req.FollowerId), req.PrevIndex, time.Second)`

req.PrevIndex is the applied index returns from raft.AppliedIndex().

Get err: `configuration changed since 9 (latest is 1)` (last index is less than the applied?).

I checked AppliedIndex of every server, all of them were same.

**Comment by ncabatoff** [comment]
Hi @kotyara85,

I'm having trouble understanding exactly what you're describing, could you provide more details please?

@838239178, would you mind filing a new ticket for your issue please?  It's usually better not to assume that an existing bug report is the same thing you're experiencing, let us mark it as a duplicate if we determine that.

**Comment by kotyara85** [comment]
@ncabatoff 
Raft calls callback func on each restart and reapplies all logs from the beginning,
I'd expect it to apply only logs which are missing.

**Comment by JoanFM** [comment]
> @ncabatoff Raft calls apply func on each restart and reapplies all logs from the beginning, I'd expect it to apply only logs which are missing.

Hello @kotyara85 ,

As far as I know, this seems to be reasonable. At restart the Raft node will try to restablish its state by doing 2 things:

`Restore` snapshots if present, and apply the logs which are not considered inside the `snapshot`. My bet is that you do not have the `snapshot` logic implemented or the `snapshot` logic is not executed during the lifetime of the service before it restarts.

I hope you find it useful.

**Comment by ncabatoff** [comment]
Thanks @JoanFM, I agree with your comment and that this seems to be working as expected.

**Comment by evanxg852000** [comment]
@JoanFM In my case I am running a single node raft. When commands are applied, I expect the appliedIndex to be reflected upon restart. But when my node restart from a state, it even changes config to a single node cluster, become a candidate as if it was not the leader in the previous term. then it reapplies all the log from index 0 and up

**Comment by otoolep** [comment]
This is the way these systems work, at least in their easiest-to-understand, most robust way.

On restart the state (KV store, in-memory structures, database) is blown away, and rebuilt entirely from the Raft log. Sometimes that rebuild involves starting with a Snapshot, and replaying any logs that are not in the Snapshot.

**Comment by evanxg852000** [comment]
Thank you @otoolep, I guess the best way is to throw away the db.file and recreate it using the logs. In essence, the logs with a snapshot are the single source of truth.

**Comment by JoanFM** [comment]
Yes, I also think this is the expected behavior, although I do not see how it works for a single node.

**Comment by evanxg852000** [comment]
@otoolep @JoanFM, Please is there any discord channel or an appropriate place to ask such question? This is more of a beginner question than a issue.

Please, is reading the whole binary kv file `db.file` and sending it as a snapshot a good strategy then?
Currently, I export the key-values as a set of INSERT and compress them, then re-import them one at a time during **restore**.  
I think it's just easier to read and compress the `db.file` during the snapshot. Then uncompress it and save it as the node `db.file` during **restore**

**Comment by otoolep** [comment]
> Thank you @otoolep, I guess the best way is to throw away the db.file and recreate it using the logs. In essence, the logs with a snapshot are the single source of truth.

Of course. The Raft log is the only authoritative source of truth. That has always been the case. Perhaps you all would like to watch my latest GopherCon presentation, which talks about this library and the topics on this issue.

https://www.youtube.com/watch?v=8XbxQ1Epi5w&t=3s

**Comment by otoolep** [comment]
> Yes, I also think this is the expected behavior, although I do not see how it works for a single node.

Why? Why wouldn't it work for a single node? Again, the Raft log (and any snapshots) contain the entire history of the state machine from the start of time.

**Comment by otoolep** [comment]
> @otoolep @JoanFM, Please is there any discord channel or an appropriate place to ask such question? This is more of a beginner question than a issue.
> 
> Please, is reading the whole binary kv file `db.file` and sending it as a **snapshot** a good strategy then? Currently, I export the key-values as a set of INSERT and compress them during the **snapshot**, then re-import them one at a time during **restore**. I think it's just easier to read and compress the `db.file` during the **snapshot**. Then uncompress it and save it as the node `db.file` during **restore**

Yes, that is one approach. It's exactly how rqlite works, which uses the Hashicorp library. A snapshot is simply a copy of the entire SQLite database as it sits on disk.

https://rqlite.io/docs/design/

**Comment by JoanFM** [comment]
I mean it should work, but with one Node I guess there is no consensus to be met.

**Comment by otoolep** [comment]
> I mean it should work, but with one Node I guess there is no consensus to be met.

Well technically there is still a consensus requirement. It's just requires one node to be in consensus.

**Comment by JoanFM** [comment]
Sure.

**Comment by evanxg852000** [comment]
No the library doesn't impose a minimum cluster size and this is great because you want to seamlessly provide the fault-tolerance feature without much code.
A fault-tolerant cluster starts with three nodes, but any setup below should work fine without a fault-tolerance guaranty.

**Comment by JoanFM** [comment]
Thanks @evanxg852000, nice to know
