### ISSUE TITLE
Tests are unstable

### ISSUE THREAD

**Issue by aviau** [hashicorp/raft#55]
Hello!

I have packaged hashicorp/raft for Debian. (Available in unstable [here](https://tracker.debian.org/pkg/golang-github-hashicorp-raft))

Sometimes, the tests fail. You may see the logs [here](https://reproducible.debian.net/rb-pkg/unstable/amd64/golang-github-hashicorp-raft.html)

The error we are getting is 
```
--- FAIL: TestRaft_LeaderFail (0.33s)
	raft_test.go:511: expected new leader
```

And some other times: 
```
--- FAIL: TestRaft_LeaderLeaseExpire (0.18s)
	raft_test.go:1292: bad: 69f816ea-8214-d42c-015a-e4320f2ebac8
```

The tests pass about 50% of the time.

Is this a known issue?

Thanks,

**Comment by ryanuber** [comment]
Hey @aviau,

I haven't seen that particular error before, but there are some cases we have seen tests fail intermittently. It's likely a problem with the tests, where they just need to be more lenient to timing. Thanks for opening the report, we will take a look.

**Comment by stapelberg** [comment]
Even more of the tests than previously thought are actually failing: https://bugs.debian.org/796469

We’ll need to disable the tests entirely for now. Can you please take a look?

**Comment by ongardie** [comment]
This is still an issue.

One thing I've done in the past is clearly name all the tests that are dependent on timing (CPU speed, timeouts) so that they could be treated differently. For example in LogCabin these all have "TimingSensitive" in the name, and Travis-CI is configured not to count those test failures as build failures. At least by clearly labeling them, we can start to distinguish real test failures from flakiness.

Ran 100 tests against master (`for i in {1..100}; do go test -timeout=5s 2>&1 | head -n 1; done`), sorted the first line of the output. Looks like at least 7 of them are flaky:
```
--- FAIL: TestRaft_ApplyConcurrent (0.16s)
--- FAIL: TestRaft_Barrier (0.12s)
--- FAIL: TestRaft_BehindFollower (0.06s)
--- FAIL: TestRaft_BehindFollower (0.06s)
--- FAIL: TestRaft_BehindFollower (0.07s)
--- FAIL: TestRaft_BehindFollower (0.07s)
--- FAIL: TestRaft_BehindFollower (0.07s)
--- FAIL: TestRaft_BehindFollower (0.08s)
--- FAIL: TestRaft_BehindFollower (0.08s)
--- FAIL: TestRaft_BehindFollower (0.09s)
--- FAIL: TestRaft_BehindFollower (0.09s)
--- FAIL: TestRaft_BehindFollower (0.10s)
--- FAIL: TestRaft_BehindFollower (0.10s)
--- FAIL: TestRaft_BehindFollower (0.10s)
--- FAIL: TestRaft_BehindFollower (0.11s)
--- FAIL: TestRaft_JoinNode (0.06s)
--- FAIL: TestRaft_SnapshotRestore_PeerChange (0.08s)
--- FAIL: TestRaft_SnapshotRestore_PeerChange (0.09s)
--- FAIL: TestRaft_SnapshotRestore_PeerChange (0.16s)
--- FAIL: TestRaft_SnapshotRestore_PeerChange (0.17s)
--- FAIL: TestRaft_SnapshotRestore_PeerChange (0.17s)
--- FAIL: TestRaft_TripleNode (0.49s)
--- FAIL: TestRaft_Voting (0.06s)
--- FAIL: TestRaft_Voting (0.07s)
--- FAIL: TestRaft_Voting (0.07s)
--- FAIL: TestRaft_Voting (0.08s)
--- FAIL: TestRaft_Voting (0.08s)
--- FAIL: TestRaft_Voting (0.08s)
--- FAIL: TestRaft_Voting (0.08s)
--- FAIL: TestRaft_Voting (0.08s)
--- FAIL: TestRaft_Voting (0.16s)
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
```

**Comment by abligh** [comment]
Pull request #91 fixed a similar thing for me. I'm not convinced I got all of them, but I now can't get it to fail without `-race`. Sadly the mechanisms of the `TestRaft_` tests are entirely timing dependent, which means if the machine is loaded, they are prone to failure.

**Comment by slackpad** [comment]
Going to close this out as #111 is merged where @abligh made for a more deterministic wait strategy using an observer that gets notified of Raft events, which has beefed up the robustness of the tests. There are some less frequent flaky tests but those are captured in other issues.

**Comment by onlyjob** [comment]
`TestRaft_SnapshotRestore_PeerChange` is still failing for me...
