### ISSUE TITLE
raft.Snapshot() snapshots to 0 if there are no new log entries

### ISSUE THREAD

**Issue by superfell** [hashicorp/raft#56]
I've noticed that under certain conditions if you force a snapshot to be created via raft.Snapshot() it reports that its snapshot'd to 0, e.g.

10:07:45 graphr3 | 2015/08/05 10:07:45 [INFO] raft: Starting snapshot up to 0
10:07:45 graphr3 | 2015/08/05 10:07:45 [INFO] snapshot: Creating new snapshot at /media/data/code/graphr/data/3/snapshots/0-0-1438794465718.tmp
10:07:45 graphr3 | 2015/08/05 10:07:45 [INFO] snapshot: reaping snapshot /media/data/code/graphr/data/3/snapshots/0-0-1438794465718
10:07:45 graphr3 | 2015/08/05 10:07:45 [INFO] raft: Compacting logs from 385002 to 0
10:07:45 graphr3 | 2015/08/05 10:07:45 [INFO] raft: Snapshot to 0 complete

The easiest way to reproduce this is to start a node, force a snapshot, stop the node, restart it, and then force a snapshot again. It seems like something doesn't get initialized until a new log entry has been created.

**Comment by superfell** [comment]
So the problem seems to be in raft.runFSM(), the lastIndex & lastTerm variables are local to the func, are only set when there's a commit or a restore called for, but the initial load of the snapshot at startup is done outside of that via restoreSnapshot(). so if the first request that runFSM() seens is to create a snapshot, it hasn't set lastIndex & lastTerm yet.

**Comment by armon** [comment]
@superfell This is an interesting one. I'm not sure what the correct behavior is in this case. The snapshot really is capturing nothing if there is no commits or restores prior to this, so that part is correct. We should be calling `restoreSnapshot()` before returning the `Raft` instance, so I'm not even sure how this is possible.

**Comment by superfell** [comment]
From what i could tell, the initial snapshot load at startup doesn't go through the FSM goroutine.

It seems like either it should spot this and return an error for the snapshot attempt (as there's nothing new that would require a snapshot), or the FSM goroutine should initialize it index/term local vars from the Raft instance. I'd be happy to code up either solution if you have a prefernce [i mostly lean towards having the snapshot attempt return an error]

**Comment by armon** [comment]
@superfell Agreed, it is strange to snapshot when there is no data. Lets go with the error return.
