### ISSUE TITLE
getting notified on losing follower heartbeat

### ISSUE THREAD

**Issue by mahditakrim** [hashicorp/raft#565]
Is there any way to get notified if leader lost follower heartbeat, so we can do some logic in that situation ?

**Comment by otoolep** [comment]
I haven't used it myself, but I presume the leader should register for this event: https://pkg.go.dev/github.com/hashicorp/raft#FailedHeartbeatObservation

**Comment by otoolep** [comment]
Actually, I forgot rqlite *does* use that observation, to reap failed nodes. See.

https://github.com/rqlite/rqlite/blob/master/store/store.go#L438

**Comment by mahditakrim** [comment]
> Actually, I forgot rqlite _does_ use that observation, to reap failed nodes. See.
> 
> https://github.com/rqlite/rqlite/blob/master/store/store.go#L438

One more question, can i assume that getting "FailedHeartbeatObservation" means node is down or will be down in seconds ?
