### ISSUE TITLE
Push to the notify channel  and shutdown sign  arriving,it is  pick one of two but actually nobody know  which one

### ISSUE THREAD

**Issue by SchopenhauerZhang** [hashicorp/raft#566]
i test code found it, i  am not sure it is a bug or it is designned; but it is weird;

When Push to the notify channel  ,received shutdown sign.we  know it is pick one of two,but actually run which one,God knows.

follow the code ,https://github.com/hashicorp/raft/blob/main/raft.go#L434
```
notify := r.config().NotifyCh

	// Push to the notify channel if given
	if notify != nil {
		select {
		case notify <- true:
		case <-r.shutdownCh:
		}
	}

```

**Comment by SchopenhauerZhang** [comment]
@ncabatoff 
Sorry, I am very slow to reply, there are too many daily chores. 
I recall that when I first discovered this problem, my thoughts were: 
During local testing, I found that the behavior here was unknowable, which caused trouble for the test. As a user, I still hope that every behavior is clear and try to avoid it (Ambiguous behavior). Ambiguous behavior should be avoided in programming and coding, right? So I think there's something wrong here.
Of course, I still hope that everyone will discuss and criticize more, and my thinking may not be perfect.

**Comment by SchopenhauerZhang** [comment]
I still need to see ,Will it cause other unknown problems, such as:
if this problem will cause a piece of logic to be lost in the shutdown phase.

**Comment by SchopenhauerZhang** [comment]
My English is poor,Please remind me if I didn't explain clearly.
(By the way ,I used Google Translation :-| )

**Comment by banks** [comment]
Thanks for the PR @SchopenhauerZhang! 

It looks like that's merged so I'm going to close this issue now. Thanks for your contribution ❤️ .
