### ISSUE TITLE
Hard code in error handling

### ISSUE THREAD

**Issue by icexin** [hashicorp/raft#57]
In https://github.com/hashicorp/raft/blob/master/raft.go#L172, using `err.Error() != "not found"` to check missing key makes implementing `StableStore` confused. Maybe using `ErrKeyNotFound` as what `ErrLogNotFound` does can be better.

**Comment by armon** [comment]
@icexin Good call, that would probably be cleaner.

**Comment by catsby** [comment]
Hello - I just merged #370 to make this a `var`
