### ISSUE TITLE
How to bootstrap a raft cluster with a single node?

### ISSUE THREAD

**Issue by shreyaskaundinya** [hashicorp/raft#573]
Question/Help wanted : 

I have a use case where there is a possibility of a single node being used. I would like to know how to bootstrap a single node cluster.

Bootstrap cluster configuration : 

```go
config := raft.Configuration{
  Servers: []raft.Server{
	  {
		  ID:       conf.LocalID,
		  Address:  transport.LocalAddr(),
		  Suffrage: raft.Voter,
	  },
  },
}
```

Raft server config : 

```go
conf := raft.DefaultConfig()

conf.LocalID = raft.ServerID(fmt.Sprintf("%d", AppConfig.Id))
conf.Logger = &utils.ModLogger{
  Logger: zap.NewExample().Sugar(),
}
conf.BatchApplyCh = false
```

**Comment by otoolep** [comment]
You just do it. Pass config containing the node itself and call `raft.Bootstrap()`.

https://pkg.go.dev/github.com/hashicorp/raft#Raft.BootstrapCluster

rqlite does it here, if it detects it's coming up as a single node (trace the code to learn more):

https://github.com/rqlite/rqlite/blob/master/cmd/rqlited/main.go#L486

For a simpler example:

https://github.com/otoolep/hraftd

**Comment by ncabatoff** [comment]
Thanks @otoolep, I feel this answers the question so I'll close this issue.
