### ISSUE TITLE
Logging destinations

### ISSUE THREAD

**Issue by superfell** [hashicorp/raft#60]
the raft type takes a log.Logger for logging, but other parts (transport / snapshots ) take a writer instead.

It'd be useful if everything took a log.Logger, or even better if there was a simple interface that defined the logging methods, and users could provide their own impl to their favorite logging destination. [a simple interface here would also make it easier to route logging to testing.T.log during tests]

**Comment by armon** [comment]
Moving everything to a `log.Logger` should be pretty straightforward, since I think we wrap the Writer anyways in that.

**Comment by armon** [comment]
Fixed in #61
