### ISSUE TITLE
[DOC] How does the master know if one of the followers is partitioned?

### ISSUE THREAD

**Issue by kingluo** [hashicorp/raft#615]
Suppose we have 3 nodes, A is the master node, B and C are slave nodes. If the network between A and B fails, B will become a candidate node and be partitioned. How does A know this fact?

**Comment by otoolep** [comment]
Raft uses heartbeating to detect node failures. It's all explained clearly in the Raft paper.

https://raft.github.io/raft.pdf

**Comment by kingluo** [comment]
Yes I know, but I want to know how the golang function gets notified of this event. [RegisterObserver()](https://pkg.go.dev/github.com/hashicorp/raft#Observation) doesn't seem to cover this event. I hope that on the A side, I can know that B becomes a candidate or is partitioned from A and C.

**Comment by otoolep** [comment]
You want to register for https://pkg.go.dev/github.com/hashicorp/raft#FailedHeartbeatObservation

**Comment by banks** [comment]
> I hope that on the A side, I can know that B becomes a candidate or is partitioned from A and C.

I'd be curious what you are trying to do with this information. @otoolep pointed out that it's possible to observe _on the leader node_ when a heartbeat fails. But you can't for sure know things like whether that node has actually failed, is partitioned, or is just slow (maybe CPU overloaded or network switch congested). You also can't guarantee or reason about it being in an particular raft state (like candidate) even if it's not connected or responding. This is all impossible in an async network (see the FLP result).

If you're just trying to log some messages for operators to help debug that might be OK, but you should be very careful about trying to use observations like this to actually take actions in your software! You are basically now building a new distributed algorithm that isn't raft and (history teach is) is unlikely to be correct unless you spend a lot of time model checking and getting lots of other experts to review it!

**Comment by otoolep** [comment]
Agree with @banks

**Comment by otoolep** [comment]
https://en.wikipedia.org/wiki/XY_problem

**Comment by kingluo** [comment]
Yes, I agree with both of you. In fact, the event I really need is the heartbeat failure on the master. Is it one of the variants of `Observation`? But the documentation does not mention this type of event, that's why I ask this question.

```go
type FailedHeartbeatObservation struct {
	PeerID      [ServerID](https://pkg.go.dev/github.com/hashicorp/raft#ServerID)
	LastContact [time](https://pkg.go.dev/time).[Time](https://pkg.go.dev/time#Time)
}
type Observation struct {
	// Raft holds the Raft instance generating the observation.
	Raft *[Raft](https://pkg.go.dev/github.com/hashicorp/raft#Raft)
	// Data holds observation-specific data. Possible types are
	// RequestVoteRequest
	// RaftState
	// PeerObservation
	// LeaderObservation
	Data interface{}
}
```

I found it really emits `FailedHeartbeatObservation` in the code:

https://github.com/hashicorp/raft/blob/42d34464b2d203e389e11ed6d43db698792c0604/replication.go#L411
