### ISSUE TITLE
Graceful leader removal

### ISSUE THREAD

**Issue by lmars** [hashicorp/raft#62]
I am attempting to gracefully stop a daemon which is participating in Raft consensus by calling `RemovePeer` and then exiting, but in the case of that daemon being the leader, this has the effect of [removing all other peers](https://github.com/hashicorp/raft/blob/master/raft.go#L1152) rather than just the leader.

I see there is a [stepDown channel](https://github.com/hashicorp/raft/blob/master/raft.go#L853-L854) (triggered [when the leader has a stale term](https://github.com/hashicorp/raft/blob/master/replication.go#L490-L495)), but that just transitions to a follower leaving the daemon in a position where it may get elected once again.

What I want is a way to remove the leader and leave the rest of the cluster in a state where it will elect a new leader without requiring the current leader to vote.

Is this possible? I am happy to make changes if someone can point me in the right direction.

**Comment by corylanou** [comment]
I'm pretty sure I just hit the same thing when setting up `DROP SERVER` for influxDB.  I'm going to use `SetPeers` instead of `RemovePeer` and see if that works instead as a workaround (even though it's considered unsafe).  Currently, if I use `SetPeer` everyone in my raft peer group drops to a follower.

**Comment by shlomi-noach** [comment]
I suggest https://github.com/hashicorp/raft/pull/222, where the `Yield()` function instructs a node to not attempt becoming a leader for some duration.
