### ISSUE TITLE
Is there any way to get membership with status?

### ISSUE THREAD

**Issue by kingluo** [hashicorp/raft#627]
For example, if there are three nodes, A is the master and is active, B is active, and C is offline, then from B's perspective, can I get a membership of the form `[A: active, B: active, C: offline]`?

**Comment by otoolep** [comment]
You need to reach out to those nodes and see if you can contact them over the network rqlite does this.

https://github.com/rqlite/rqlite/blob/master/http/service.go#L967

**Comment by otoolep** [comment]
You could also register for Heartbeat observations (gain and loss) and store that state. See the Godocs for this library.

**Comment by kingluo** [comment]
> You could also register for Heartbeat observations (gain and loss) and store that state. See the Godocs for this library.

yes, but it seems that only the master can receive this kind of observation, after all, no heartbeat is needed between followers. So far, I have chosen this way.
