### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by junshotin** [hashicorp/raft#628]
I just learned about Raft. How can I explain how this project has started

**Comment by dhyanio** [comment]
@junshotin Discache using raft for consensus here https://github.com/dhyanio/discache/blob/main/raft/raft.go.
This might be the easiest way to implement Raft in your project. 
Here in Discache we are using an HTTP server for the client.

**Comment by junshotin** [comment]
When I clicked on the link you provided, it displayed a 404 page not found

> @junshotin Discache using raft for consensus here https://github.com/dhyanio/discache/blob/main/rafter/raft.go. This might be the easiest way to implement Raft in your project. Here in Discache we are using an HTTP server for the client.

**Comment by dhyanio** [comment]
@junshotin For me it is working https://github.com/dhyanio/discache/blob/main/rafter/raft.go

**Comment by mpalmi** [comment]
Hello @junshotin! Thanks for taking an interest in the project. We have a couple of example implementations in our README, if you want to take a look: https://github.com/hashicorp/raft#community-contributed-examples

If you're interested in reading more about Raft and some other implementations out there, you might find this site helpful: https://raft.github.io/

I'm going to go ahead and close this out for now. Please let us know if you have any further questions!
