### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by mikkazan** [hashicorp/raft#63]
I am new to go. Need to implement go version of raft client. Got your project, complied but cannot find any file to run. Assumed it could be raft.go but got this error back

C:\go_workspace\raft>go run raft.go
go run: cannot run non-main package

Thanks for your help.

**Comment by ryanuber** [comment]
Hey @mikkazan,

This project is a library which provides a consensus protocol primitive to be used in other Go applications. It does not itself have a main runloop or provide a means for running as a server process, and is not usable all on its own. The library is used both in [consul](https://github.com/hashicorp/consul) and [nomad](https://github.com/hashicorp/nomad), so if you'd like you can check those projects out as a reference. You can also see the usage reference at [godoc](https://godoc.org/github.com/hashicorp/raft).

Hope that helps!

**Comment by mikkazan** [comment]
OK thanks
