### ISSUE TITLE
Node doesn't vote for current leader

### ISSUE THREAD

**Issue by superfell** [hashicorp/raft#74]
Part of the voting rules is that a node won't vote for another node if it thinks there's an active leader. However it applies this rule even when the node asking for the vote is the node that the voter thinks is the leader. e.g. (here node lp_0 refuses to vote for lp_3 because it thinks lp_3 is the leader)

lp_0:17:03:33.954809 [WARN] raft: Rejecting vote from lp_3 since we have a leader: lp_3

Seems like if the node asking for the vote is the node we think is the leader we should go ahead and vote for it.

**Comment by superfell** [comment]
Perhaps the real problem is that replicateTo will continue to send AE requests after its stepped down as leader. [it looks like this doesn't stop until a new leader is elected]

**Comment by superfell** [comment]
One possible fix would be to add the stopCh to the select list in replicateTo, this would break the feature where it tries to replicate upto a known index when a peer is removed, however various places read the stopCh and loose this replicate up to index number, so its not clear that it works consistently anyway.

If the replicate to an index on peer removal is needed, then it seems like there probably needs to be 2 stop channels, one for an unconditional stop, and one for stop at this index.

Trying to continue to replicate to Index point X (where X was decided while still leader) but no longer leader seems dangerous.

**Comment by armon** [comment]
@superfell I think this is a race condition, in that AE may be inflight already when the leader steps down. We do stop replication immediately on step down, but things may already have been inflight.

**Comment by armon** [comment]
I think allowing a vote for the current leader seems fine, since the node's state is still logically consistent.

**Comment by superfell** [comment]
My thinking ended up all over the map on this one, but in the end that was the conclusion i came to as well. [but got distracted by the other issue]. Happy to put together a PR for that.

**Comment by armon** [comment]
@superfell Sounds good, I'll keep an eye out for the PR.
