### ISSUE TITLE
remove peer, re-add later fails to connect

### ISSUE THREAD

**Issue by cpuguy83** [hashicorp/raft#78]
Having a weird issue, assuming I'm doing something wrong...

I have a cluster, if I remove a peer (and actually remove it from the peer list), the raft lib works as expected, stops trying to connect to the peer and everything.
If I re-add that peer to the cluster later on, the peer is successfully added however the leader is unable to connect to it.

In the leader logs I get this over and over: `DEBUG] raft: Failed to contact 172.17.0.5:2377 in <time>`
And `Failed to heartbeat to 172.17.0.5:2377: read tcp 172.17.0.3:34570->172.17.0.5:2377: i/o timeout`

In the re-added peer log I get this over and over `raft-net: 172.17.0.5:2380 accepted connection from: 172.17.0.3:34570`

Reading TCP dump, it seems like the peer is sending back a 0 byte response on each connection attempt.

**_note that of course the port numbers of course change after each connection attempt**_

When the peer is simply disconnected and re-connected (not actually removed from the peer list), everything syncs back up as expected.

This is not a problem with a specific node, it's on any node that I remove then re-add.

This is happening with both my own peer store implementation and stream layer implementations, as well as the standard JSON Peer and TCP Transport/stream layer.

It also happens if I remove all the existing state on the re-added node (prior to adding, after removing).
It also continues to happen when a new leader is elected (on the new leader).

**Comment by superfell** [comment]
I've seen this behavior as well, its related to the ShutdownOnRemove config option, which defaults to true. Once the node processes the log entry to say remove it, it shuts down raft processing, and doesn't handle any of the subsequent messages to add it back to the cluster. Deleting the nodes state doesn't help, as the log gets replicated over and replayed anyway. [unless you can get to the point where the removal messages are aged out by a snapshot] To me it feels like there needs to be some kind of membership identity that separate to the nodes name or address (although I haven't fully thought through this yet)

**Comment by cpuguy83** [comment]
:+1: Setting this to false seems to have fixed my issue.
Based on the description of this option that is somewhat surprising behavior, as the description seems to be about the local node only.

**Comment by ianwoolf** [comment]
It work to me as well. 

In my case, new node not cannot add to the cluster if it removed one peer. And the removed peer cannot add to the cluster too.  Setting this to false seems to fix it.

**Comment by GitRainy** [comment]
i have same problem,in my test,i use three node A,B,C; i start all of them and A will become leader.when i shutdown B and then restart B, the B can be readded to cluster  correctly. But when i shutdown  A and then restart A,the A can't be readded to cluster correctly. error is as follows

> 2018/10/09 16:21:42 [INFO] raft: Updating configuration with AddStaging (node0, 127.0.0.1:0) to [{Suffrage:Voter ID:node1 Address:127.0.0.1:1} {Suffrage:Voter ID:node2 Address:127.0.0.1:2} {Suffrage:Voter ID:node0 Address:127.0.0.1:0}]
2018/10/09 16:21:42 [INFO] raft: Added peer node0, starting replication
2018/10/09 16:21:42 [ERR] raft: Failed to AppendEntries to {Voter node0 127.0.0.1:0}: dial tcp 127.0.0.1:0: connectex: The requested address is not valid in its context.
[store] 2018/10/09 16:21:42 node node0 at 127.0.0.1:0 joined successfully
[] 
2018/10/09 16:21:42 [ERR] raft: Failed to AppendEntries to {Voter node0 127.0.0.1:0}: dial tcp 127.0.0.1:0: connectex: The requested address is not valid in its context.
