### ISSUE TITLE
Removing the leader can lead to different log's applied to the remaining nodes

### ISSUE THREAD

**Issue by superfell** [hashicorp/raft#79]
While doing some stress testing we ran into this issue. If you do a RemovePeer of a node who happens to be the leader at the time, and is also working on other outstanding Apply'd entries, the remaining nodes in the cluster can end up seeing a mismatch in the entries that are applied to the FSMs. In particular some nodes will see one entry applied and other node never see this entry (depending on the entry this can lead to serious data issues).

The entry in question always appears to be an inflight entry that is the log entry after the RemovePeers log entry. e.g. in this run log entry 3827 was the RemovePeer entry, node 0's FSM saw this sequence of Apply's (term/index/data)
1.    3825: 7945C0282719297129F2A5F85B89E9D55373600FA459F8BA7BFD9D443488635A67
1.    3826: BF921247A73A9AFDAD5D2A37D34C4C49636C6353D0173AE6D29682C11685FD6E07
3.    3829: A74CC536489C8AFD48EAA6A5FB2063614E16E15EA13754B362A8A448A7A49CBB75
3.    3830: 6E98BE940FF0CFD71960DBA7C9B3674D18BA97ECAACC8B80DF7211F9702AFF77D7

but node 3's FSM saw these sequence of applies
1.    3825: 7945C0282719297129F2A5F85B89E9D55373600FA459F8BA7BFD9D443488635A67
1.    3826: BF921247A73A9AFDAD5D2A37D34C4C49636C6353D0173AE6D29682C11685FD6E07
__1.    3828: 7340F10D4B683B02B08A37077C90CC4B39A7812C4A87EF986190679031DDDB9526__
3.    3829: A74CC536489C8AFD48EAA6A5FB2063614E16E15EA13754B362A8A448A7A49CBB75
3.    3830: 6E98BE940FF0CFD71960DBA7C9B3674D18BA97ECAACC8B80DF7211F9702AFF77D7

Note the extra log entry at 3828 that Node 3 saw that Node 0 didn't. (Node 1 was the leader which was the node removed)

In addition, the client request that created log entry 3828 was given a success result.

We added some instrumentation of AppendEntry RPC calls to our transport, and from that log we see this sequence of AE's from the leader at this time
node from -> to, first/last index in message, leaderCommitIndex
rl_1 -> rl_2	    3823 -     3824 :     3820
rl_1 -> rl_4	    3825 -     3826 :     3822
rl_1 -> rl_2	    3825 -     3826 :     3822
rl_1 -> rl_0	    3821 -     3824 :     3820
rl_1 -> rl_3	    3825 -     3827 :     3822
rl_1 -> rl_0	    3825 -     3826 :     3822
rl_1 -> rl_2	    3827 -     3827 :     3822
rl_1 -> rl_0	    3827 -     3827 :     3822
rl_1 -> rl_4	    3827 -     3827 :     3828
rl_1 -> rl_3	    3828 -     3828 :     3828
rl_1 -> rl_2	       0 -        0 :     3828
rl_1 -> rl_0	       0 -        0 :     3828
rl_1 -> rl_3	       0 -        0 :     3828

everything looks normal (commit index slightly lagging the log entries as you'd expect) until you get to the RemovePeer entry. note how the leaderCommitIndex jumps to 3828, even though its only ever sent to one node.

Digging through the code, what appears to be happening is that membership changes get applied in 2 steps, raft.go line 926 explicitly makes an additional call to processLog with precommit=true. In ProccessLog, line 1161, if we're removing ourselves r.peers is set to nil. regular log processing continue now, with dispatchLogs being called. At line 1074, the quorum policy for the log entries is created with `applyLog.policy = newMajorityQuorum(len(r.peers) + 1)` however at this point r.peers is now nil, and so the quorum is based on 1, and not the actual cluster size, as this log entry proceeds to the inflight list, its meets its quorum needs and is immediately committed.

the leader then proceeds with the regular call to ProcessLog which completes the removal of the leader, which tells the replication to only replicate upto the RemovePeer entry, which exacerbates the problem, based on timing only some small subset of the other nodes have the log entry after the RemovePeer. (but based on the leaderCommitIndex, any node that has the next log entry will apply it to its FSM). 

[I'll be attaching a pull request to this issue that updates the RemoveLeader test to demonstrate this issue].

It seems like in the case where a node is being removed (including itself) ProcessLog shouldn't update r.peers unless precommit is false. [but I need to walk through that somemore]

**Comment by armon** [comment]
@superfell This is a pretty bad issue. Thanks for digging in. I think we should merge the test changes in once we have a fix, so that the tests are not always failing.

**Comment by superfell** [comment]
Sure, that's reasonable.

**Comment by armon** [comment]
@superfell So thinking about this, I feel like the right behavior is for all transactions after the RemovePeer to be subject to `ErrLeadershipLost`. Assuming totally serial behavior, after the RemovePeer(leader) finishes, nothing is expected to make progress on the leader. Does this make sense?

**Comment by superfell** [comment]
Makes sense to me. In terms of a fix, i'm currently running tests on adding a !precommit check around the r.peers = nil / r.peerStore.SetPeers([]string{r.localAddr}) pair in processLog (~line 1161). I think that means you may see one or two additional log entries go along with the removePeer, but they'll be managed correctly.

**Comment by armon** [comment]
@superfell Take a look at PR #81. I think that should fix the issue, so far I haven't been able to get a test failure.
